MLIR: lib/Dialect/SCF/Utils/AffineCanonicalizationUtils.cpp File Reference
AffineCanonicalizationUtils.cpp File Reference
#include "mlir/Dialect/SCF/Utils/AffineCanonicalizationUtils.h"
#include "mlir/Dialect/Affine/Analysis/AffineStructures.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "mlir-scf-affine-utils"
Functions
static void unpackOptionalValues (ArrayRef< Optional< Value >> source, SmallVector< Value > &target)
static LogicalResult alignAndAddBound (FlatAffineValueConstraints &constraints, IntegerPolyhedron::BoundType type, unsigned pos, AffineMap map, ValueRange operands)
Bound an identifier pos in a given FlatAffineValueConstraints with constraints drawn from an affine map.
static AffineMap addConstToResults (AffineMap map, int64_t val)
Add val to each result of map.
static LogicalResult addLoopRangeConstraints (FlatAffineValueConstraints &constraints, Value iv, OpFoldResult lb, OpFoldResult ub, OpFoldResult step, RewriterBase &rewriter)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlir-scf-affine-utils"
Definition at line 23 of file AffineCanonicalizationUtils.cpp.
Function Documentation
addConstToResults()
static AffineMap addConstToResults (AffineMap map, int64_t val) static
Add val to each result of map.
Definition at line 57 of file AffineCanonicalizationUtils.cpp.
References mlir::AffineMap::get(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by mlir::scf::canonicalizeMinMaxOp().
addLoopRangeConstraints()
static LogicalResult addLoopRangeConstraints (FlatAffineValueConstraints & constraints, Value iv, OpFoldResult lb, OpFoldResult ub, OpFoldResult step, RewriterBase & rewriter) static
Definition at line 164 of file AffineCanonicalizationUtils.cpp.
References mlir::FlatAffineValueConstraints::addBound(), mlir::presburger::IntegerRelation::addInequality(), mlir::FlatAffineValueConstraints::appendDimVar(), mlir::FlatAffineValueConstraints::appendSymbolVar(), mlir::presburger::IntegerRelation::EQ, mlir::failure(), mlir::presburger::floorDiv(), mlir::AffineMap::get(), mlir::Builder::getAffineConstantExpr(), mlir::Builder::getAffineSymbolExpr(), mlir::getConstantIntValue(), mlir::presburger::IntegerRelation::getNumCols(), mlir::presburger::IntegerRelation::getNumDimVars(), mlir::presburger::IntegerRelation::getNumSymbolVars(), and mlir::presburger::IntegerRelation::UB.
Referenced by mlir::scf::canonicalizeMinMaxOpInLoop().
alignAndAddBound()
static LogicalResult alignAndAddBound (FlatAffineValueConstraints & constraints, IntegerPolyhedron::BoundType type, unsigned pos, AffineMap map, ValueRange operands) static
Bound an identifier pos in a given FlatAffineValueConstraints with constraints drawn from an affine map.
Before adding the constraint, the dimensions/symbols of the affine map are aligned with constraints. operands are the SSA Value operands used with the affine map. Note: This function adds a new symbol column to the constraints for each dimension/symbol that exists in the affine map but not in constraints.
Definition at line 41 of file AffineCanonicalizationUtils.cpp.
References mlir::FlatAffineValueConstraints::addBound(), mlir::alignAffineMapWithValues(), mlir::FlatAffineValueConstraints::appendSymbolVar(), mlir::FlatAffineValueConstraints::getMaybeValues(), mlir::presburger::SetDim, mlir::presburger::Symbol, and unpackOptionalValues().
Referenced by mlir::scf::canonicalizeMinMaxOp().
unpackOptionalValues()
static void unpackOptionalValues (ArrayRef< Optional< Value >> source, SmallVector< Value > & target) static
Definition at line 28 of file AffineCanonicalizationUtils.cpp.
Referenced by alignAndAddBound(), and mlir::scf::canonicalizeMinMaxOp().