MLIR: lib/Dialect/AMDGPU/IR/AMDGPUDialect.cpp File Reference
AMDGPUDialect.cpp File Reference
#include "mlir/Dialect/AMDGPU/AMDGPUDialect.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/TypeSwitch.h"
#include <limits>
#include "mlir/Dialect/AMDGPU/AMDGPUDialect.cpp.inc"
#include "mlir/Dialect/AMDGPU/AMDGPU.cpp.inc"
#include "mlir/Dialect/AMDGPU/AMDGPUAttributes.cpp.inc"
#include "mlir/Dialect/AMDGPU/AMDGPUEnums.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_ATTRDEF_LIST
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
Functions
template<typename T >
static LogicalResult verifyRawBufferOp (T &op)
static Optional< uint32_t > getConstantUint32 (Value v)
template<typename OpType >
static bool staticallyOutOfBounds (OpType op)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 222 of file AMDGPUDialect.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 225 of file AMDGPUDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getConstantUint32()
static Optional<uint32_t> getConstantUint32 (Value v) static
Definition at line 70 of file AMDGPUDialect.cpp.
References mlir::Value::getType(), mlir::Type::isInteger(), mlir::m_ConstantInt(), and mlir::matchPattern().
Referenced by staticallyOutOfBounds().
staticallyOutOfBounds()
template<typename OpType > static bool staticallyOutOfBounds (OpType op) static
Definition at line 80 of file AMDGPUDialect.cpp.
References mlir::failed(), getConstantUint32(), mlir::getStridesAndOffset(), and max().
verifyRawBufferOp()
template<typename T > static LogicalResult verifyRawBufferOp (T & op) static
Definition at line 48 of file AMDGPUDialect.cpp.
References mlir::success().