MLIR: mlir::sparse_tensor::SparseTensorSpecifier Class Reference
mlir::sparse_tensor::SparseTensorSpecifier Class Reference
#include "Dialect/SparseTensor/Transforms/SparseTensorStorageLayout.h"
Public Member Functions
SparseTensorSpecifier (Value specifier)
operator Value ()
Value getSpecifierField (OpBuilder &builder, Location loc, StorageSpecifierKind kind, Optional< unsigned > dim)
void setSpecifierField (OpBuilder &builder, Location loc, Value v, StorageSpecifierKind kind, Optional< unsigned > dim)
Type getFieldType (StorageSpecifierKind kind, Optional< unsigned > dim)
Static Public Member Functions
static Value getInitValue (OpBuilder &builder, Location loc, RankedTensorType rtp)
Detailed Description
Definition at line 125 of file SparseTensorStorageLayout.h.
Constructor & Destructor Documentation
SparseTensorSpecifier()
mlir::sparse_tensor::SparseTensorSpecifier::SparseTensorSpecifier (Value specifier) inline explicit
Definition at line 127 of file SparseTensorStorageLayout.h.
Member Function Documentation
getFieldType()
Type mlir::sparse_tensor::SparseTensorSpecifier::getFieldType (StorageSpecifierKind kind, Optional< unsigned > dim) inline
Definition at line 141 of file SparseTensorStorageLayout.h.
Referenced by getSpecifierField(), and setSpecifierField().
getInitValue()
Value SparseTensorSpecifier::getInitValue (OpBuilder & builder, Location loc, RankedTensorType rtp) static
Definition at line 92 of file SparseTensorStorageLayout.cpp.
References mlir::OpBuilder::create(), and mlir::sparse_tensor::getSparseTensorEncoding().
getSpecifierField()
Value SparseTensorSpecifier::getSpecifierField (OpBuilder & builder, Location loc, StorageSpecifierKind kind, Optional< unsigned > dim)
Definition at line 98 of file SparseTensorStorageLayout.cpp.
References mlir::OpBuilder::create(), createIndexCast(), fromOptionalInt(), getFieldType(), and mlir::Builder::getIndexType().
Referenced by mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getSpecifierField().
operator Value()
mlir::sparse_tensor::SparseTensorSpecifier::operator Value () inline
Definition at line 133 of file SparseTensorStorageLayout.h.
setSpecifierField()
void SparseTensorSpecifier::setSpecifierField (OpBuilder & builder, Location loc, Value v, StorageSpecifierKind kind, Optional< unsigned > dim)
Definition at line 108 of file SparseTensorStorageLayout.cpp.
References mlir::OpBuilder::create(), createIndexCast(), fromOptionalInt(), and getFieldType().
Referenced by mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::setSpecifierField().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/Transforms/SparseTensorStorageLayout.h
lib/Dialect/SparseTensor/Transforms/SparseTensorStorageLayout.cpp