MLIR: SpecifierStructBuilder Class Reference
SpecifierStructBuilder Class Reference
Public Member Functions
SpecifierStructBuilder (Value specifier)
Value dimSize (OpBuilder &builder, Location loc, unsigned dim)
Builds IR inserting the pos-th size into the descriptor.
void setDimSize (OpBuilder &builder, Location loc, unsigned dim, Value size)
Builds IR inserting the pos-th size into the descriptor.
Value memSize (OpBuilder &builder, Location loc, unsigned pos)
Builds IR extracting the pos-th memory size into the descriptor.
void setMemSize (OpBuilder &builder, Location loc, unsigned pos, Value size)
Builds IR inserting the pos-th memory size into the descriptor.
Public Member Functions inherited from mlir::StructBuilder
StructBuilder (Value v)
Construct a helper for the given value.
operator Value ()
Static Public Member Functions
static Value getInitValue (OpBuilder &builder, Location loc, Type structType)
Static Public Member Functions inherited from mlir::StructBuilder
static StructBuilder undef (OpBuilder &builder, Location loc, Type descriptorType)
Builds IR creating an undef value of the descriptor type.
Additional Inherited Members
Protected Member Functions inherited from mlir::StructBuilder
Value extractPtr (OpBuilder &builder, Location loc, unsigned pos)
Builds IR to extract a value from the struct at position pos.
void setPtr (OpBuilder &builder, Location loc, unsigned pos, Value ptr)
Builds IR to set a value in the struct at position pos.
Protected Attributes inherited from mlir::StructBuilder
Value value
Type structType
Detailed Description
Definition at line 45 of file SparseStorageSpecifierToLLVM.cpp.
Constructor & Destructor Documentation
SpecifierStructBuilder()
SpecifierStructBuilder::SpecifierStructBuilder (Value specifier) inline explicit
Definition at line 47 of file SparseStorageSpecifierToLLVM.cpp.
References value.
Member Function Documentation
dimSize()
Value SpecifierStructBuilder::dimSize (OpBuilder & builder, Location loc, unsigned dim)
Builds IR inserting the pos-th size into the descriptor.
Definition at line 78 of file SparseStorageSpecifierToLLVM.cpp.
References mlir::OpBuilder::create(), kDimSizePosInSpecifier, and value.
Referenced by StorageSpecifierGetOpConverter::onDimSize().
getInitValue()
Value SpecifierStructBuilder::getInitValue (OpBuilder & builder, Location loc, Type structType) static
Definition at line 61 of file SparseStorageSpecifierToLLVM.cpp.
References mlir::Type::cast(), mlir::sparse_tensor::constantZero(), mlir::OpBuilder::create(), and kMemSizePosInSpecifier.
Referenced by StorageSpecifierInitOpConverter::matchAndRewrite().
memSize()
Value SpecifierStructBuilder::memSize (OpBuilder & builder, Location loc, unsigned pos)
Builds IR extracting the pos-th memory size into the descriptor.
Definition at line 92 of file SparseStorageSpecifierToLLVM.cpp.
References mlir::OpBuilder::create(), kMemSizePosInSpecifier, and value.
Referenced by StorageSpecifierGetOpConverter::onMemSize().
setDimSize()
void SpecifierStructBuilder::setDimSize (OpBuilder & builder, Location loc, unsigned dim, Value size)
Builds IR inserting the pos-th size into the descriptor.
Definition at line 85 of file SparseStorageSpecifierToLLVM.cpp.
References mlir::OpBuilder::create(), kDimSizePosInSpecifier, and value.
Referenced by StorageSpecifierSetOpConverter::onDimSize().
setMemSize()
void SpecifierStructBuilder::setMemSize (OpBuilder & builder, Location loc, unsigned pos, Value size)
Builds IR inserting the pos-th memory size into the descriptor.
Definition at line 99 of file SparseStorageSpecifierToLLVM.cpp.
References mlir::OpBuilder::create(), kMemSizePosInSpecifier, and value.
Referenced by StorageSpecifierSetOpConverter::onMemSize().
The documentation for this class was generated from the following file:
lib/Dialect/SparseTensor/Transforms/SparseStorageSpecifierToLLVM.cpp