MLIR: mlir::sparse_tensor::SparseTensorDescriptorImpl< mut > Class Template Reference
mlir::sparse_tensor::SparseTensorDescriptorImpl< mut > Class Template Reference
A helper class around an array of values that corresponding to a sparse tensor, provides a set of meaningful APIs to query and update a particular field in a consistent way.
#include "Dialect/SparseTensor/Transforms/SparseTensorStorageLayout.h"
Public Member Functions
SparseTensorDescriptorImpl (Type tp, ValueArrayRef fields)
template<typename T = SparseTensorDescriptorImpl<true>>
SparseTensorDescriptorImpl (std::enable_if_t<!mut, T > &mDesc)
unsigned getMemRefFieldIndex (SparseTensorFieldKind kind, Optional< unsigned > dim) const
unsigned getPtrMemRefIndex (unsigned ptrDim) const
unsigned getIdxMemRefIndex (unsigned idxDim) const
unsigned getValMemRefIndex () const
unsigned getNumFields () const
Value getSpecifierField (OpBuilder &builder, Location loc, StorageSpecifierKind kind, Optional< unsigned > dim) const
Getters: get the value for required field.
Value getDimSize (OpBuilder &builder, Location loc, unsigned dim) const
Value getPtrMemSize (OpBuilder &builder, Location loc, unsigned dim) const
Value getIdxMemSize (OpBuilder &builder, Location loc, unsigned dim) const
Value getValMemSize (OpBuilder &builder, Location loc) const
Value getPtrMemRef (unsigned ptrDim) const
Value getIdxMemRef (unsigned idxDim) const
Value getValMemRef () const
Value getMemRefField (SparseTensorFieldKind kind, Optional< unsigned > dim) const
Value getMemRefField (unsigned fidx) const
Value getField (unsigned fidx) const
template<typename T = Value>
void setMemRefField (SparseTensorFieldKind kind, Optional< unsigned > dim, std::enable_if_t< mut, T > v)
Setters: update the value for required field (only enabled for MutSparseTensorDescriptor).
template<typename T = Value>
void setMemRefField (unsigned fidx, std::enable_if_t< mut, T > v)
template<typename T = Value>
void setField (unsigned fidx, std::enable_if_t< mut, T > v)
template<typename T = Value>
void setSpecifierField (OpBuilder &builder, Location loc, StorageSpecifierKind kind, Optional< unsigned > dim, std::enable_if_t< mut, T > v)
template<typename T = Value>
void setDimSize (OpBuilder &builder, Location loc, unsigned dim, std::enable_if_t< mut, T > v)
ValueRange getMemRefFields () const
Type getMemRefElementType (SparseTensorFieldKind kind, Optional< unsigned > dim) const
RankedTensorType getTensorType () const
ValueArrayRef getFields () const
Detailed Description
template<bool mut>
class mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >
A helper class around an array of values that corresponding to a sparse tensor, provides a set of meaningful APIs to query and update a particular field in a consistent way.
Users should not make assumption on how a sparse tensor is laid out but instead relies on this class to access the right value for the right field.
Definition at line 155 of file SparseTensorStorageLayout.h.
Constructor & Destructor Documentation
SparseTensorDescriptorImpl() [1/2]
template<bool mut> mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::SparseTensorDescriptorImpl (Type tp, ValueArrayRef fields) inline
Definition at line 169 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::getNumFieldsFromEncoding(), and mlir::sparse_tensor::getSparseTensorEncoding().
SparseTensorDescriptorImpl() [2/2]
template<bool mut> template<typename T = SparseTensorDescriptorImpl<true>> mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::SparseTensorDescriptorImpl (std::enable_if_t<!mut, T > & mDesc) inline
Definition at line 183 of file SparseTensorStorageLayout.h.
Member Function Documentation
getDimSize()
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getDimSize (OpBuilder & builder, Location loc, unsigned dim) const inline
Definition at line 218 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getSpecifierField().
getField()
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getField (unsigned fidx) const inline
Definition at line 259 of file SparseTensorStorageLayout.h.
getFields()
template<bool mut> ValueArrayRef mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getFields () const inline
Definition at line 317 of file SparseTensorStorageLayout.h.
Referenced by mlir::sparse_tensor::genTuple().
getIdxMemRef()
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getIdxMemRef (unsigned idxDim) const inline
Definition at line 241 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefField(), and mlir::sparse_tensor::IdxMemRef.
getIdxMemRefIndex()
template<bool mut> unsigned mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getIdxMemRefIndex (unsigned idxDim) const inline
Definition at line 197 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefFieldIndex(), and mlir::sparse_tensor::IdxMemRef.
getIdxMemSize()
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getIdxMemSize (OpBuilder & builder, Location loc, unsigned dim) const inline
Definition at line 227 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getSpecifierField().
getMemRefElementType()
template<bool mut> Type mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefElementType (SparseTensorFieldKind kind, Optional< unsigned > dim) const inline
Definition at line 308 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefField(), and mlir::Value::getType().
getMemRefField() [1/2]
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefField (SparseTensorFieldKind kind, Optional< unsigned > dim) const inline
Definition at line 249 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefFieldIndex().
Referenced by mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getIdxMemRef(), mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefElementType(), mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getPtrMemRef(), and mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getValMemRef().
getMemRefField() [2/2]
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefField (unsigned fidx) const inline
Definition at line 254 of file SparseTensorStorageLayout.h.
getMemRefFieldIndex()
template<bool mut> unsigned mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefFieldIndex (SparseTensorFieldKind kind, Optional< unsigned > dim) const inline
Definition at line 186 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::StorageLayout::getMemRefFieldIndex(), and mlir::sparse_tensor::getSparseTensorEncoding().
Referenced by mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getIdxMemRefIndex(), mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefField(), mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getPtrMemRefIndex(), mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getValMemRefIndex(), and mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::setMemRefField().
getMemRefFields()
template<bool mut> ValueRange mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefFields () const inline
Definition at line 302 of file SparseTensorStorageLayout.h.
getNumFields()
template<bool mut> unsigned mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getNumFields () const inline
Definition at line 205 of file SparseTensorStorageLayout.h.
getPtrMemRef()
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getPtrMemRef (unsigned ptrDim) const inline
Definition at line 237 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefField(), and mlir::sparse_tensor::PtrMemRef.
getPtrMemRefIndex()
template<bool mut> unsigned mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getPtrMemRefIndex (unsigned ptrDim) const inline
Definition at line 193 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefFieldIndex(), and mlir::sparse_tensor::PtrMemRef.
getPtrMemSize()
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getPtrMemSize (OpBuilder & builder, Location loc, unsigned dim) const inline
Definition at line 222 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getSpecifierField().
getSpecifierField()
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getSpecifierField (OpBuilder & builder, Location loc, StorageSpecifierKind kind, Optional< unsigned > dim) const inline
Getters: get the value for required field.
Definition at line 211 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorSpecifier::getSpecifierField().
Referenced by mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getDimSize(), mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getIdxMemSize(), mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getPtrMemSize(), and mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getValMemSize().
getTensorType()
template<bool mut> RankedTensorType mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getTensorType () const inline
Definition at line 316 of file SparseTensorStorageLayout.h.
Referenced by mlir::sparse_tensor::genTuple().
getValMemRef()
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getValMemRef () const inline
Definition at line 245 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefField(), and mlir::sparse_tensor::ValMemRef.
getValMemRefIndex()
template<bool mut> unsigned mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getValMemRefIndex () const inline
Definition at line 201 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefFieldIndex(), and mlir::sparse_tensor::ValMemRef.
getValMemSize()
template<bool mut> Value mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getValMemSize (OpBuilder & builder, Location loc) const inline
Definition at line 232 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getSpecifierField().
setDimSize()
template<bool mut> template<typename T = Value> void mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::setDimSize (OpBuilder & builder, Location loc, unsigned dim, std::enable_if_t< mut, T > v) inline
Definition at line 297 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::setSpecifierField().
setField()
template<bool mut> template<typename T = Value> void mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::setField (unsigned fidx, std::enable_if_t< mut, T > v) inline
Definition at line 282 of file SparseTensorStorageLayout.h.
setMemRefField() [1/2]
template<bool mut> template<typename T = Value> void mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::setMemRefField (SparseTensorFieldKind kind, Optional< unsigned > dim, std::enable_if_t< mut, T > v) inline
Setters: update the value for required field (only enabled for MutSparseTensorDescriptor).
Definition at line 270 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::getMemRefFieldIndex().
setMemRefField() [2/2]
template<bool mut> template<typename T = Value> void mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::setMemRefField (unsigned fidx, std::enable_if_t< mut, T > v) inline
Definition at line 276 of file SparseTensorStorageLayout.h.
setSpecifierField()
template<bool mut> template<typename T = Value> void mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::setSpecifierField (OpBuilder & builder, Location loc, StorageSpecifierKind kind, Optional< unsigned > dim, std::enable_if_t< mut, T > v) inline
Definition at line 288 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::SparseTensorSpecifier::setSpecifierField().
Referenced by mlir::sparse_tensor::SparseTensorDescriptorImpl< mut >::setDimSize().
The documentation for this class was generated from the following file:
lib/Dialect/SparseTensor/Transforms/SparseTensorStorageLayout.h