MLIR: mlir::sparse_tensor::CodegenEnv Class Reference
mlir::sparse_tensor::CodegenEnv Class Reference
The code generation environment class aggregates a number of data structures that are needed during the code generation phase of sparsification.
#include "Dialect/SparseTensor/Transforms/CodegenEnv.h"
Public Member Functions
CodegenEnv (linalg::GenericOp linop, SparsificationOptions opts, unsigned numTensors, unsigned numLoops, unsigned numFilterLoops)
Constructs a code generation environment which can be passed around during sparsification for bookkeeping together with some consistency asserts.
linalg::GenericOp op () const
const SparsificationOptions & options () const
Merger & merger ()
LoopEmitter & emitter ()
void startEmit (OpOperand *so, unsigned lv)
Optional< Operation * > genLoopBoundary (function_ref< Optional< Operation * >(MutableArrayRef< Value > parameters)> callback)
Generates loop boundary statements (entering/exiting loops).
TensorExp & exp (unsigned e)
LatPoint & lat (unsigned l)
SmallVector< unsigned > & set (unsigned s)
DimLevelType dlt (unsigned t, unsigned i) const
DimLevelType dlt (unsigned b) const
size_t topSortSize () const
unsigned topSortAt (unsigned i) const
void topSortPushBack (unsigned i)
void topSortClear (unsigned capacity=0)
ArrayRef< unsigned > getTopSortSlice (size_t n, size_t m) const
ArrayRef< unsigned > getLoopCurStack () const
Value getLoopIdxValue (size_t loopIdx) const
bool hasSparseOutput () const
bool isSparseOutput (OpOperand *o) const
Value getInsertionChain () const
void updateInsertionChain (Value chain)
bool atExpandLevel (OpOperand *o, unsigned rank, unsigned lv) const
void startExpand (Value values, Value filled, Value added, Value count)
bool isExpand () const
void updateExpandCount (Value count)
Value getExpandValues () const
Value getExpandFilled () const
Value getExpandAdded () const
Value getExpandCount () const
void endExpand ()
void startReduc (unsigned exp, Value val)
bool isReduc () const
void updateReduc (Value val)
Value getReduc () const
Value endReduc ()
void startCustomReduc (unsigned exp)
bool isCustomReduc () const
Value getCustomRedId ()
void endCustomReduc ()
Detailed Description
The code generation environment class aggregates a number of data structures that are needed during the code generation phase of sparsification.
This environment simplifies passing around such data during sparsification (rather than passing around all the individual compoments where needed). Furthermore, it provides convience methods that keep implementation details transparent to sparsification while asserting on internal consistency.
Definition at line 34 of file CodegenEnv.h.
Constructor & Destructor Documentation
CodegenEnv()
CodegenEnv::CodegenEnv (linalg::GenericOp linop, SparsificationOptions opts, unsigned numTensors, unsigned numLoops, unsigned numFilterLoops)
Constructs a code generation environment which can be passed around during sparsification for bookkeeping together with some consistency asserts.
Definition at line 18 of file CodegenEnv.cpp.
Member Function Documentation
atExpandLevel()
bool CodegenEnv::atExpandLevel (OpOperand * o, unsigned rank, unsigned lv) const
Definition at line 96 of file CodegenEnv.cpp.
Referenced by genExpand().
dlt() [1/2]
DimLevelType mlir::sparse_tensor::CodegenEnv::dlt (unsigned b) const inline
Definition at line 69 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::getDimLevelType().
dlt() [2/2]
DimLevelType mlir::sparse_tensor::CodegenEnv::dlt (unsigned t, unsigned i) const inline
Definition at line 66 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::getDimLevelType().
Referenced by computeIterationGraph(), genFor(), genIf(), and isAdmissibleTensorExp().
emitter()
LoopEmitter& mlir::sparse_tensor::CodegenEnv::emitter () inline
Definition at line 49 of file CodegenEnv.h.
Referenced by endLoop(), endLoopSeq(), genBuffers(), genConstantDenseAddressFromLevel(), genExpand(), genFor(), genIf(), genInsertionStore(), genResult(), genSubscript(), genWhile(), and startLoop().
endCustomReduc()
void CodegenEnv::endCustomReduc ()
Definition at line 151 of file CodegenEnv.cpp.
Referenced by genExp(), and genInvariants().
endExpand()
void CodegenEnv::endExpand ()
Definition at line 114 of file CodegenEnv.cpp.
Referenced by genExpand().
endReduc()
Value CodegenEnv::endReduc ()
Definition at line 134 of file CodegenEnv.cpp.
References updateReduc().
Referenced by genInvariants().
exp()
TensorExp& mlir::sparse_tensor::CodegenEnv::exp (unsigned e) inline
Definition at line 63 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::exp().
Referenced by genExp(), genInvariants(), genInvariantValue(), genTensorLoad(), genTensorStore(), getCustomRedId(), startCustomReduc(), startReduc(), and updateReduc().
genLoopBoundary()
Optional< Operation * > CodegenEnv::genLoopBoundary (function_ref< Optional< Operation * >(MutableArrayRef< Value > parameters)> callback)
Generates loop boundary statements (entering/exiting loops).
The function passes and updates the passed-in parameters.
Definition at line 47 of file CodegenEnv.cpp.
References isExpand(), isReduc(), updateExpandCount(), updateInsertionChain(), and updateReduc().
Referenced by endLoop(), genFor(), and genWhile().
getCustomRedId()
Value CodegenEnv::getCustomRedId ()
Definition at line 146 of file CodegenEnv.cpp.
References exp(), and op().
Referenced by genInsertionLoadReduce(), and genInvariants().
getExpandAdded()
Value mlir::sparse_tensor::CodegenEnv::getExpandAdded () const inline
Definition at line 105 of file CodegenEnv.h.
Referenced by genExpand(), and genInsertionStore().
getExpandCount()
Value mlir::sparse_tensor::CodegenEnv::getExpandCount () const inline
Definition at line 106 of file CodegenEnv.h.
Referenced by endIf(), finalizeWhileOp(), genExpand(), genInsertionStore(), and genStmt().
getExpandFilled()
Value mlir::sparse_tensor::CodegenEnv::getExpandFilled () const inline
Definition at line 104 of file CodegenEnv.h.
Referenced by genExpand(), genInsertionLoadReduce(), and genInsertionStore().
getExpandValues()
Value mlir::sparse_tensor::CodegenEnv::getExpandValues () const inline
Definition at line 103 of file CodegenEnv.h.
Referenced by genExpand(), genInsertionLoad(), genInsertionLoadReduce(), and genInsertionStore().
getInsertionChain()
Value mlir::sparse_tensor::CodegenEnv::getInsertionChain () const inline
Definition at line 96 of file CodegenEnv.h.
Referenced by endIf(), finalizeWhileOp(), genExpand(), genIf(), genInsertionStore(), genResult(), genStmt(), and genTensorStore().
getLoopCurStack()
ArrayRef< unsigned > CodegenEnv::getLoopCurStack () const
Definition at line 76 of file CodegenEnv.cpp.
References mlir::sparse_tensor::LoopEmitter::getCurrentDepth(), and getTopSortSlice().
Referenced by isInvariantAffine().
getLoopIdxValue()
Value CodegenEnv::getLoopIdxValue (size_t loopIdx) const
Definition at line 80 of file CodegenEnv.cpp.
References mlir::sparse_tensor::LoopEmitter::getLoopIV().
Referenced by endLoopSeq(), genIf(), genIndex(), genIndexValue(), genInvariants(), and startLoopSeq().
getReduc()
Value mlir::sparse_tensor::CodegenEnv::getReduc () const inline
Definition at line 116 of file CodegenEnv.h.
Referenced by endIf(), finalizeWhileOp(), genIf(), and genStmt().
getTopSortSlice()
ArrayRef< unsigned > CodegenEnv::getTopSortSlice (size_t n, size_t m) const
Definition at line 72 of file CodegenEnv.cpp.
Referenced by getLoopCurStack(), and permute().
hasSparseOutput()
bool mlir::sparse_tensor::CodegenEnv::hasSparseOutput () const inline
Definition at line 93 of file CodegenEnv.h.
Referenced by isParallelFor().
isCustomReduc()
bool mlir::sparse_tensor::CodegenEnv::isCustomReduc () const inline
Definition at line 120 of file CodegenEnv.h.
Referenced by genInvariants(), and genTensorLoad().
isExpand()
bool mlir::sparse_tensor::CodegenEnv::isExpand () const inline
Definition at line 101 of file CodegenEnv.h.
Referenced by endIf(), finalizeWhileOp(), genIf(), genInsertionLoad(), genInsertionLoadReduce(), genInsertionStore(), genLoopBoundary(), and isParallelFor().
isReduc()
bool mlir::sparse_tensor::CodegenEnv::isReduc () const inline
Definition at line 114 of file CodegenEnv.h.
Referenced by endIf(), finalizeWhileOp(), genExpand(), genIf(), genLoopBoundary(), and genTensorStore().
isSparseOutput()
bool mlir::sparse_tensor::CodegenEnv::isSparseOutput (OpOperand * o) const inline
Definition at line 94 of file CodegenEnv.h.
Referenced by genTensorLoad(), and genTensorStore().
lat()
LatPoint& mlir::sparse_tensor::CodegenEnv::lat (unsigned l) inline
Definition at line 64 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::lat().
Referenced by endLoop(), genStmt(), startLoopSeq(), and translateBitsToTidDimPairs().
merger()
Merger& mlir::sparse_tensor::CodegenEnv::merger () inline
Definition at line 48 of file CodegenEnv.h.
Referenced by computeIterationGraph(), findSparseAnnotations(), genExp(), genFor(), genIf(), genInvariants(), genStmt(), isAdmissibleTensorExp(), permute(), startLoop(), startLoopSeq(), topSortOptimal(), and translateBitsToTidDimPairs().
op()
linalg::GenericOp mlir::sparse_tensor::CodegenEnv::op () const inline
Definition at line 46 of file CodegenEnv.h.
Referenced by computeIterationGraph(), endIf(), endLoop(), finalizeWhileOp(), findSparseAnnotations(), genBuffers(), genConstantDenseAddressFromLevel(), genExp(), genExpand(), genFor(), genIf(), genIndex(), genInitConstantDenseAddress(), genInsertionLoad(), genInsertionLoadReduce(), genInsertionStore(), genInvariants(), genResult(), genSubscript(), genTensorLoad(), genTensorStore(), genWhile(), getCustomRedId(), isAdmissibleTensorExp(), permute(), startLoop(), and translateBitsToTidDimPairs().
options()
const SparsificationOptions& mlir::sparse_tensor::CodegenEnv::options () const inline
Definition at line 47 of file CodegenEnv.h.
Referenced by isParallelFor().
set()
SmallVector<unsigned>& mlir::sparse_tensor::CodegenEnv::set (unsigned s) inline
Definition at line 65 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::set().
Referenced by genStmt(), and startLoopSeq().
startCustomReduc()
void CodegenEnv::startCustomReduc (unsigned exp)
Definition at line 141 of file CodegenEnv.cpp.
References exp().
Referenced by genExp(), and genInvariants().
startEmit()
void CodegenEnv::startEmit (OpOperand * so, unsigned lv)
Definition at line 27 of file CodegenEnv.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::sparse_tensor::LoopEmitter::initialize(), and mlir::sparse_tensor::Merger::setHasSparseOut().
startExpand()
void CodegenEnv::startExpand (Value values, Value filled, Value added, Value count)
Definition at line 100 of file CodegenEnv.cpp.
Referenced by genExpand().
startReduc()
void CodegenEnv::startReduc (unsigned exp, Value val)
Definition at line 123 of file CodegenEnv.cpp.
References exp(), and updateReduc().
Referenced by genInvariants().
topSortAt()
unsigned mlir::sparse_tensor::CodegenEnv::topSortAt (unsigned i) const inline
Definition at line 78 of file CodegenEnv.h.
Referenced by genLoop(), genStmt(), isAdmissibleTensorExp(), permute(), and startLoop().
topSortClear()
void mlir::sparse_tensor::CodegenEnv::topSortClear (unsigned capacity = 0) inline
Definition at line 80 of file CodegenEnv.h.
Referenced by computeIterationGraph().
topSortPushBack()
void mlir::sparse_tensor::CodegenEnv::topSortPushBack (unsigned i) inline
Definition at line 79 of file CodegenEnv.h.
Referenced by topSortOptimal().
topSortSize()
size_t mlir::sparse_tensor::CodegenEnv::topSortSize () const inline
Definition at line 77 of file CodegenEnv.h.
Referenced by genLoop(), genStmt(), permute(), and topSortOptimal().
updateExpandCount()
void CodegenEnv::updateExpandCount (Value count)
Definition at line 109 of file CodegenEnv.cpp.
Referenced by endIf(), finalizeWhileOp(), genInsertionStore(), and genLoopBoundary().
updateInsertionChain()
void CodegenEnv::updateInsertionChain (Value chain)
Definition at line 91 of file CodegenEnv.cpp.
Referenced by endIf(), finalizeWhileOp(), genExpand(), genInsertionStore(), genLoopBoundary(), and genTensorStore().
updateReduc()
void CodegenEnv::updateReduc (Value val)
Definition at line 129 of file CodegenEnv.cpp.
References exp(), and mlir::sparse_tensor::TensorExp::val.
Referenced by endIf(), endReduc(), finalizeWhileOp(), genLoopBoundary(), genTensorStore(), and startReduc().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/Transforms/CodegenEnv.h
lib/Dialect/SparseTensor/Transforms/CodegenEnv.cpp