MLIR: mlir::sparse_tensor::Merger Class Reference
mlir::sparse_tensor::Merger Class Reference
A class to handle all iteration lattice operations.
#include "mlir/Dialect/SparseTensor/Utils/Merger.h"
Public Member Functions
Merger (unsigned t, unsigned l, unsigned fl)
Constructs a merger for the given number of tensors, native loops, and filter loops.
unsigned addExp (Kind k, unsigned e0, unsigned e1=-1u, Value v=Value(), Operation *op=nullptr)
Adds a tensor expression. Returns its index.
unsigned addExp (Kind k, unsigned e, Value v, Operation *op=nullptr)
unsigned addExp (Kind k, Value v, Operation *op=nullptr)
unsigned addLat (unsigned t, unsigned i, unsigned e)
Adds an iteration lattice point. Returns its index.
unsigned addSet ()
Adds a new, initially empty, set. Returns its index.
unsigned conjLatPoint (Kind kind, unsigned p0, unsigned p1, Operation *op=nullptr)
Computes a single conjunction of two lattice points by taking the "union" of loop indices (effectively constructing a larger "intersection" of those indices) with a newly constructed tensor (sub)expression of given kind.
unsigned takeConj (Kind kind, unsigned s0, unsigned s1, Operation *op=nullptr)
Conjunctive merge of two lattice sets L0 and L1 is conjunction of cartesian product.
unsigned takeDisj (Kind kind, unsigned s0, unsigned s1, Operation *op=nullptr)
Disjunctive merge of two lattice sets L0 and L1 is (L0 /_op L1, L0, L1).
unsigned takeCombi (Kind kind, unsigned s0, unsigned s1, Operation *orig, bool includeLeft, Kind ltrans, Operation *opleft, bool includeRight, Kind rtrans, Operation *opright)
Disjunctive merge of two lattice sets L0 and L1 with custom handling of the overlap, left, and right regions.
unsigned mapSet (Kind kind, unsigned s0, Value v=Value(), Operation *op=nullptr)
Maps the unary operator over the lattice set of the operand, i.e.
unsigned optimizeSet (unsigned s0)
Optimizes the iteration lattice points in the given set.
BitVector simplifyCond (unsigned s0, unsigned p0)
Simplifies the conditions in a conjunction of a given lattice point within the given set using just two basic rules: (1) multiple dense conditions are reduced to single dense, and (2) a singleton sparse/dense is reduced to sparse/random access.
bool latGT (unsigned i, unsigned j) const
Returns true if Li > Lj.
bool onlyDenseDiff (unsigned i, unsigned j)
Returns true if Li and Lj only differ in dense.
unsigned tensor (unsigned b) const
Bit translation (get tensor ID).
unsigned index (unsigned b) const
Bit translation (get loop index).
unsigned getNumLoops () const
Get the number of total loops (native loops + filter loops).
unsigned getNumNativeLoops () const
Get the number of native loops.
unsigned getNumFilterLoops () const
Get the number of filter loops.
unsigned getFilterLoopStartingIdx () const
Get the starting filter loop index.
bool isOutTensor (unsigned b, unsigned i) const
Returns true if bit corresponds to index of output tensor.
unsigned getOutTensorID () const
Gets tensor ID for the output tensor.
unsigned getSynTensorID () const
Gets tensor ID for the synthetic tensor (used for all invariant tensor expressions).
bool isFilterLoop (unsigned ldx) const
bool expContainsTensor (unsigned e, unsigned t) const
Returns true if the expression contains the t as an operand.
bool hasNegateOnOut (unsigned e) const
Returns true if the expression contains a negation on output tensor.
bool isSingleCondition (unsigned t, unsigned e) const
Returns true if given tensor iterates only in the given tensor expression.
bool hasAnySparse (const BitVector &bits) const
Returns true if any set bit corresponds to sparse dimension level type.
DimLevelType getDimLevelType (unsigned t, unsigned i) const
Gets the dimension level type of the tth tensor on ith loop.
DimLevelType getDimLevelType (unsigned b) const
Gets the dimension level type of b.
Optional< unsigned > getLoopIdx (unsigned t, unsigned dim) const
Optional< unsigned > getDimNum (unsigned t, unsigned i) const
Gets the dimension number of the the tth tensor on ith loop.
Optional< unsigned > getDimNum (unsigned b) const
Gets the dimension number of b.
void setDimAndDimLevelType (unsigned t, unsigned i, unsigned dim, DimLevelType dlt)
Sets the dimension and dimension level type of the tth tensor on ith loop.
void foreachTidDimPairInBits (const BitVector &bits, function_ref< void(unsigned b, unsigned tid, Optional< unsigned > dim, DimLevelType dlt)> cb)
void setHasSparseOut (bool s)
TensorExp & exp (unsigned e)
Convenience getters to immediately access the stored nodes.
LatPoint & lat (unsigned l)
SmallVector< unsigned > & set (unsigned s)
void dumpExp (unsigned e) const
Print methods (for debugging).
void dumpLat (unsigned p) const
void dumpSet (unsigned s) const
void dumpBits (const BitVector &bits) const
unsigned buildLattices (unsigned e, unsigned i)
Builds the iteration lattices in a bottom-up traversal given the remaining tensor (sub)expression and the next loop index in the iteration graph.
Optional< unsigned > buildTensorExpFromLinalg (linalg::GenericOp op)
Builds a tensor expression from the given Linalg operation.
Value buildExp (RewriterBase &rewriter, Location loc, unsigned e, Value v0, Value v1)
Rebuilds SSA format from a tensor expression.
Detailed Description
A class to handle all iteration lattice operations.
This class abstracts away from some implementation details of storing iteration lattices and tensor expressions. This allows for fine-tuning performance characteristics independently from the basic algorithm if bottlenecks are identified.
Definition at line 149 of file Merger.h.
Constructor & Destructor Documentation
Merger()
mlir::sparse_tensor::Merger::Merger (unsigned t, unsigned l, unsigned fl)
Constructs a merger for the given number of tensors, native loops, and filter loops.
The user supplies the number of tensors involved in the kernel, with the last tensor in this set denoting the output tensor. The merger adds an additional synthetic tensor at the end of this set to represent all invariant expressions in the kernel.
In addition to natives loops (which are specified by the GenericOp), extra filter loops are needed in order to handle affine expressions on sparse dimensions. E.g., (d0, d1, d2) => (d0 + d1, d2), a naive implementation of the filter loop could be generated as
for (coord : sparse_dim[0]) if (coord == d0 + d1) { generated_code; } }
to filter out coordinates that are not equal to the affine expression.
TODO: we want to make the filter loop more efficient in the future, e.g., by avoiding scanning the full stored index sparse (keeping the last position in ordered list) or even apply binary search to find the index.
Definition at line 208 of file Merger.cpp.
References mlir::sparse_tensor::Undef.
Member Function Documentation
addExp() [1/3]
unsigned mlir::sparse_tensor::Merger::addExp (Kind k, unsigned e, Value v, Operation * op = nullptr) inline
Definition at line 179 of file Merger.h.
References addExp().
addExp() [2/3]
unsigned mlir::sparse_tensor::Merger::addExp (Kind k, unsigned e0, unsigned e1 = -1u, Value v = Value(), Operation * op = nullptr)
Adds a tensor expression. Returns its index.
Definition at line 222 of file Merger.cpp.
Referenced by addExp(), buildLattices(), conjLatPoint(), and mapSet().
addExp() [3/3]
unsigned mlir::sparse_tensor::Merger::addExp (Kind k, Value v, Operation * op = nullptr) inline
Definition at line 182 of file Merger.h.
References addExp().
addLat()
unsigned mlir::sparse_tensor::Merger::addLat (unsigned t, unsigned i, unsigned e)
Adds an iteration lattice point. Returns its index.
Definition at line 229 of file Merger.cpp.
Referenced by buildLattices().
addSet()
unsigned mlir::sparse_tensor::Merger::addSet ()
Adds a new, initially empty, set. Returns its index.
Definition at line 236 of file Merger.cpp.
Referenced by buildLattices(), mapSet(), optimizeSet(), and takeConj().
buildExp()
Value mlir::sparse_tensor::Merger::buildExp (RewriterBase & rewriter, Location loc, unsigned e, Value v0, Value v1)
Rebuilds SSA format from a tensor expression.
Definition at line 1248 of file Merger.cpp.
References mlir::sparse_tensor::buildBinaryOverlap(), mlir::sparse_tensor::buildUnaryPresent(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Value::getType(), mlir::Builder::getZeroAttr(), mlir::sparse_tensor::insertYieldOp(), mlir::sparse_tensor::kAbsC, mlir::sparse_tensor::kAbsF, mlir::sparse_tensor::kAbsI, mlir::sparse_tensor::kAddC, mlir::sparse_tensor::kAddF, mlir::sparse_tensor::kAddI, mlir::sparse_tensor::kAndI, mlir::sparse_tensor::kBinary, mlir::sparse_tensor::kBinaryBranch, mlir::sparse_tensor::kBitCast, mlir::sparse_tensor::kCastFS, mlir::sparse_tensor::kCastFU, mlir::sparse_tensor::kCastIdx, mlir::sparse_tensor::kCastS, mlir::sparse_tensor::kCastSF, mlir::sparse_tensor::kCastU, mlir::sparse_tensor::kCastUF, mlir::sparse_tensor::kCeilF, mlir::sparse_tensor::kCIm, mlir::sparse_tensor::kCRe, mlir::sparse_tensor::kDivC, mlir::sparse_tensor::kDivF, mlir::sparse_tensor::kDivS, mlir::sparse_tensor::kDivU, mlir::sparse_tensor::kExpm1C, mlir::sparse_tensor::kExpm1F, mlir::sparse_tensor::kExtF, mlir::sparse_tensor::kFloorF, mlir::sparse_tensor::kIndex, mlir::sparse_tensor::kInvariant, mlir::sparse_tensor::kLog1pC, mlir::sparse_tensor::kLog1pF, mlir::sparse_tensor::kMulC, mlir::sparse_tensor::kMulF, mlir::sparse_tensor::kMulI, mlir::sparse_tensor::kNegC, mlir::sparse_tensor::kNegF, mlir::sparse_tensor::kNegI, mlir::sparse_tensor::kOrI, mlir::sparse_tensor::kReduce, mlir::sparse_tensor::kSelect, mlir::sparse_tensor::kShlI, mlir::sparse_tensor::kShrS, mlir::sparse_tensor::kShrU, mlir::sparse_tensor::kSinC, mlir::sparse_tensor::kSinF, mlir::sparse_tensor::kSqrtC, mlir::sparse_tensor::kSqrtF, mlir::sparse_tensor::kSubC, mlir::sparse_tensor::kSubF, mlir::sparse_tensor::kSubI, mlir::sparse_tensor::kTanhC, mlir::sparse_tensor::kTanhF, mlir::sparse_tensor::kTensor, mlir::sparse_tensor::kTruncF, mlir::sparse_tensor::kTruncI, mlir::sparse_tensor::kUnary, and mlir::sparse_tensor::kXorI.
Referenced by genExp().
buildLattices()
unsigned mlir::sparse_tensor::Merger::buildLattices (unsigned e, unsigned i)
Builds the iteration lattices in a bottom-up traversal given the remaining tensor (sub)expression and the next loop index in the iteration graph.
Returns index of the root expression.
Definition at line 764 of file Merger.cpp.
References addExp(), addLat(), addSet(), mlir::Region::empty(), mlir::Region::front(), mlir::Block::getTerminator(), mlir::sparse_tensor::kAbsC, mlir::sparse_tensor::kAbsF, mlir::sparse_tensor::kAbsI, mlir::sparse_tensor::kAddC, mlir::sparse_tensor::kAddF, mlir::sparse_tensor::kAddI, mlir::sparse_tensor::kAndI, mlir::sparse_tensor::kBinary, mlir::sparse_tensor::kBinaryBranch, mlir::sparse_tensor::kBitCast, mlir::sparse_tensor::kCastFS, mlir::sparse_tensor::kCastFU, mlir::sparse_tensor::kCastIdx, mlir::sparse_tensor::kCastS, mlir::sparse_tensor::kCastSF, mlir::sparse_tensor::kCastU, mlir::sparse_tensor::kCastUF, mlir::sparse_tensor::kCeilF, mlir::sparse_tensor::kCIm, mlir::sparse_tensor::kCRe, mlir::sparse_tensor::kDivC, mlir::sparse_tensor::kDivF, mlir::sparse_tensor::kDivS, mlir::sparse_tensor::kDivU, mlir::sparse_tensor::kExpm1C, mlir::sparse_tensor::kExpm1F, mlir::sparse_tensor::kExtF, mlir::sparse_tensor::kFloorF, mlir::sparse_tensor::kIndex, mlir::sparse_tensor::kInvariant, mlir::sparse_tensor::kLog1pC, mlir::sparse_tensor::kLog1pF, mlir::sparse_tensor::kMulC, mlir::sparse_tensor::kMulF, mlir::sparse_tensor::kMulI, mlir::sparse_tensor::kNegC, mlir::sparse_tensor::kNegF, mlir::sparse_tensor::kNegI, mlir::sparse_tensor::kOrI, mlir::sparse_tensor::kReduce, mlir::sparse_tensor::kSelect, mlir::sparse_tensor::kShlI, mlir::sparse_tensor::kShrS, mlir::sparse_tensor::kShrU, mlir::sparse_tensor::kSinC, mlir::sparse_tensor::kSinF, mlir::sparse_tensor::kSqrtC, mlir::sparse_tensor::kSqrtF, mlir::sparse_tensor::kSubC, mlir::sparse_tensor::kSubF, mlir::sparse_tensor::kSubI, mlir::sparse_tensor::kTanhC, mlir::sparse_tensor::kTanhF, mlir::sparse_tensor::kTensor, mlir::sparse_tensor::kTruncF, mlir::sparse_tensor::kTruncI, mlir::sparse_tensor::kUnary, mlir::sparse_tensor::kXorI, mapSet(), takeCombi(), takeConj(), and takeDisj().
Referenced by genStmt().
buildTensorExpFromLinalg()
Optional< unsigned > mlir::sparse_tensor::Merger::buildTensorExpFromLinalg (linalg::GenericOp op)
Builds a tensor expression from the given Linalg operation.
Returns index of the root expression on success.
Definition at line 960 of file Merger.cpp.
References mlir::Region::front(), mlir::Operation::getOperand(), mlir::Operation::getRegion(), and mlir::Block::getTerminator().
conjLatPoint()
unsigned mlir::sparse_tensor::Merger::conjLatPoint (Kind kind, unsigned p0, unsigned p1, Operation * op = nullptr)
Computes a single conjunction of two lattice points by taking the "union" of loop indices (effectively constructing a larger "intersection" of those indices) with a newly constructed tensor (sub)expression of given kind.
Returns the index of the new lattice point.
Definition at line 242 of file Merger.cpp.
References addExp(), and exp().
Referenced by takeConj().
dumpBits()
void mlir::sparse_tensor::Merger::dumpBits (const BitVector & bits) const
Definition at line 747 of file Merger.cpp.
References index(), tensor(), and mlir::sparse_tensor::toMLIRString().
Referenced by dumpLat().
dumpExp()
void mlir::sparse_tensor::Merger::dumpExp (unsigned e) const
Print methods (for debugging).
Definition at line 644 of file Merger.cpp.
References mlir::sparse_tensor::kAbsC, mlir::sparse_tensor::kAbsF, mlir::sparse_tensor::kAbsI, mlir::sparse_tensor::kAddC, mlir::sparse_tensor::kAddF, mlir::sparse_tensor::kAddI, mlir::sparse_tensor::kAndI, mlir::sparse_tensor::kBinary, mlir::sparse_tensor::kBinaryBranch, mlir::sparse_tensor::kBitCast, mlir::sparse_tensor::kCastFS, mlir::sparse_tensor::kCastFU, mlir::sparse_tensor::kCastIdx, mlir::sparse_tensor::kCastS, mlir::sparse_tensor::kCastSF, mlir::sparse_tensor::kCastU, mlir::sparse_tensor::kCastUF, mlir::sparse_tensor::kCeilF, mlir::sparse_tensor::kCIm, mlir::sparse_tensor::kCRe, mlir::sparse_tensor::kDivC, mlir::sparse_tensor::kDivF, mlir::sparse_tensor::kDivS, mlir::sparse_tensor::kDivU, mlir::sparse_tensor::kExpm1C, mlir::sparse_tensor::kExpm1F, mlir::sparse_tensor::kExtF, mlir::sparse_tensor::kFloorF, mlir::sparse_tensor::kIndex, mlir::sparse_tensor::kindToOpSymbol(), mlir::sparse_tensor::kInvariant, mlir::sparse_tensor::kLog1pC, mlir::sparse_tensor::kLog1pF, mlir::sparse_tensor::kMulC, mlir::sparse_tensor::kMulF, mlir::sparse_tensor::kMulI, mlir::sparse_tensor::kNegC, mlir::sparse_tensor::kNegF, mlir::sparse_tensor::kNegI, mlir::sparse_tensor::kOrI, mlir::sparse_tensor::kReduce, mlir::sparse_tensor::kSelect, mlir::sparse_tensor::kShlI, mlir::sparse_tensor::kShrS, mlir::sparse_tensor::kShrU, mlir::sparse_tensor::kSinC, mlir::sparse_tensor::kSinF, mlir::sparse_tensor::kSqrtC, mlir::sparse_tensor::kSqrtF, mlir::sparse_tensor::kSubC, mlir::sparse_tensor::kSubF, mlir::sparse_tensor::kSubI, mlir::sparse_tensor::kTanhC, mlir::sparse_tensor::kTanhF, mlir::sparse_tensor::kTensor, mlir::sparse_tensor::kTruncF, mlir::sparse_tensor::kTruncI, mlir::sparse_tensor::kUnary, mlir::sparse_tensor::kXorI, and tensor().
Referenced by dumpLat().
dumpLat()
void mlir::sparse_tensor::Merger::dumpLat (unsigned p) const
Definition at line 728 of file Merger.cpp.
References dumpBits(), dumpExp(), and exp().
Referenced by dumpSet().
dumpSet()
void mlir::sparse_tensor::Merger::dumpSet (unsigned s) const
Definition at line 738 of file Merger.cpp.
References dumpLat().
exp()
TensorExp& mlir::sparse_tensor::Merger::exp (unsigned e) inline
Convenience getters to immediately access the stored nodes.
Typically it is inadvisible to keep the reference around, as in "TensorExpr &te = merger.exp(e))", since insertions into the merger may cause data movement and invalidate the underlying memory address.
Definition at line 343 of file Merger.h.
Referenced by conjLatPoint(), dumpLat(), mlir::sparse_tensor::CodegenEnv::exp(), and mapSet().
expContainsTensor()
bool mlir::sparse_tensor::Merger::expContainsTensor (unsigned e, unsigned t) const
Returns true if the expression contains the t as an operand.
Definition at line 398 of file Merger.cpp.
References mlir::sparse_tensor::getExpArity(), mlir::sparse_tensor::kBinary, mlir::sparse_tensor::kNullary, mlir::sparse_tensor::kTensor, mlir::sparse_tensor::kUnary, and tensor().
Referenced by hasNegateOnOut().
foreachTidDimPairInBits()
void mlir::sparse_tensor::Merger::foreachTidDimPairInBits (const BitVector & bits, function_ref< void(unsigned b, unsigned tid, Optional< unsigned > dim, DimLevelType dlt)> cb) inline
Definition at line 327 of file Merger.h.
References getDimLevelType(), getDimNum(), and tensor().
Referenced by startLoopSeq(), and translateBitsToTidDimPairs().
getDimLevelType() [1/2]
DimLevelType mlir::sparse_tensor::Merger::getDimLevelType (unsigned b) const inline
Gets the dimension level type of b.
Definition at line 294 of file Merger.h.
References getDimLevelType(), index(), and tensor().
getDimLevelType() [2/2]
DimLevelType mlir::sparse_tensor::Merger::getDimLevelType (unsigned t, unsigned i) const inline
Gets the dimension level type of the tth tensor on ith loop.
Definition at line 288 of file Merger.h.
Referenced by mlir::sparse_tensor::CodegenEnv::dlt(), findAffine(), foreachTidDimPairInBits(), genIf(), getDimLevelType(), hasAnySparse(), and simplifyCond().
getDimNum() [1/2]
Optional<unsigned> mlir::sparse_tensor::Merger::getDimNum (unsigned b) const inline
Gets the dimension number of b.
Definition at line 310 of file Merger.h.
References getDimNum(), index(), and tensor().
getDimNum() [2/2]
Optional<unsigned> mlir::sparse_tensor::Merger::getDimNum (unsigned t, unsigned i) const inline
Gets the dimension number of the the tth tensor on ith loop.
Definition at line 304 of file Merger.h.
Referenced by foreachTidDimPairInBits(), genIf(), and getDimNum().
getFilterLoopStartingIdx()
unsigned mlir::sparse_tensor::Merger::getFilterLoopStartingIdx () const inline
Get the starting filter loop index.
Definition at line 251 of file Merger.h.
References getNumNativeLoops().
Referenced by findSparseAnnotations().
getLoopIdx()
Optional<unsigned> mlir::sparse_tensor::Merger::getLoopIdx (unsigned t, unsigned dim) const inline
Definition at line 298 of file Merger.h.
Referenced by computeIterationGraph(), and genInvariants().
getNumFilterLoops()
unsigned mlir::sparse_tensor::Merger::getNumFilterLoops () const inline
Get the number of filter loops.
Definition at line 249 of file Merger.h.
Referenced by permute().
getNumLoops()
unsigned mlir::sparse_tensor::Merger::getNumLoops () const inline
Get the number of total loops (native loops + filter loops).
Definition at line 245 of file Merger.h.
Referenced by computeIterationGraph(), findSparseAnnotations(), and isAdmissibleTensorExp().
getNumNativeLoops()
unsigned mlir::sparse_tensor::Merger::getNumNativeLoops () const inline
Get the number of native loops.
Definition at line 247 of file Merger.h.
Referenced by getFilterLoopStartingIdx().
getOutTensorID()
unsigned mlir::sparse_tensor::Merger::getOutTensorID () const inline
Gets tensor ID for the output tensor.
Definition at line 259 of file Merger.h.
Referenced by startLoop().
getSynTensorID()
unsigned mlir::sparse_tensor::Merger::getSynTensorID () const inline
Gets tensor ID for the synthetic tensor (used for all invariant tensor expressions).
Definition at line 262 of file Merger.h.
hasAnySparse()
bool mlir::sparse_tensor::Merger::hasAnySparse (const BitVector & bits) const
Returns true if any set bit corresponds to sparse dimension level type.
Definition at line 533 of file Merger.cpp.
References getDimLevelType(), mlir::sparse_tensor::isCompressedDLT(), and mlir::sparse_tensor::isSingletonDLT().
Referenced by onlyDenseDiff(), and simplifyCond().
hasNegateOnOut()
bool mlir::sparse_tensor::Merger::hasNegateOnOut (unsigned e) const
Returns true if the expression contains a negation on output tensor.
I.e., - outTensor or exp - outputTensor NOTE: this is an trivial tests in that it does not handle recursive negation, i.e., it returns true when the expression is -(-tensor).
Definition at line 423 of file Merger.cpp.
References expContainsTensor(), mlir::sparse_tensor::getExpArity(), mlir::sparse_tensor::kBinary, mlir::sparse_tensor::kNegC, mlir::sparse_tensor::kNegF, mlir::sparse_tensor::kNegI, mlir::sparse_tensor::kNullary, mlir::sparse_tensor::kSubC, mlir::sparse_tensor::kSubF, mlir::sparse_tensor::kSubI, and mlir::sparse_tensor::kUnary.
Referenced by isAdmissibleTensorExp().
index()
unsigned mlir::sparse_tensor::Merger::index (unsigned b) const inline
Bit translation (get loop index).
Definition at line 242 of file Merger.h.
Referenced by dumpBits(), genIf(), getDimLevelType(), getDimNum(), and isOutTensor().
isFilterLoop()
bool mlir::sparse_tensor::Merger::isFilterLoop (unsigned ldx) const inline
Definition at line 264 of file Merger.h.
Referenced by computeIterationGraph(), genFor(), genInvariants(), isAdmissibleTensorExp(), and topSortOptimal().
isOutTensor()
bool mlir::sparse_tensor::Merger::isOutTensor (unsigned b, unsigned i) const inline
Returns true if bit corresponds to index of output tensor.
Definition at line 254 of file Merger.h.
References index(), and tensor().
isSingleCondition()
bool mlir::sparse_tensor::Merger::isSingleCondition (unsigned t, unsigned e) const
Returns true if given tensor iterates only in the given tensor expression.
For the output tensor, this defines a "simply dynamic" operation [Bik96]. For instance: a(i) *= 2.0 or a(i) += a(i) for sparse vector a.
Definition at line 449 of file Merger.cpp.
References mlir::sparse_tensor::kAbsC, mlir::sparse_tensor::kAbsF, mlir::sparse_tensor::kAbsI, mlir::sparse_tensor::kAddC, mlir::sparse_tensor::kAddF, mlir::sparse_tensor::kAddI, mlir::sparse_tensor::kAndI, mlir::sparse_tensor::kBinary, mlir::sparse_tensor::kBinaryBranch, mlir::sparse_tensor::kBitCast, mlir::sparse_tensor::kCastFS, mlir::sparse_tensor::kCastFU, mlir::sparse_tensor::kCastIdx, mlir::sparse_tensor::kCastS, mlir::sparse_tensor::kCastSF, mlir::sparse_tensor::kCastU, mlir::sparse_tensor::kCastUF, mlir::sparse_tensor::kCeilF, mlir::sparse_tensor::kCIm, mlir::sparse_tensor::kCRe, mlir::sparse_tensor::kDivC, mlir::sparse_tensor::kDivF, mlir::sparse_tensor::kDivS, mlir::sparse_tensor::kDivU, mlir::sparse_tensor::kExpm1C, mlir::sparse_tensor::kExpm1F, mlir::sparse_tensor::kExtF, mlir::sparse_tensor::kFloorF, mlir::sparse_tensor::kIndex, mlir::sparse_tensor::kInvariant, mlir::sparse_tensor::kLog1pC, mlir::sparse_tensor::kLog1pF, mlir::sparse_tensor::kMulC, mlir::sparse_tensor::kMulF, mlir::sparse_tensor::kMulI, mlir::sparse_tensor::kNegC, mlir::sparse_tensor::kNegF, mlir::sparse_tensor::kNegI, mlir::sparse_tensor::kOrI, mlir::sparse_tensor::kReduce, mlir::sparse_tensor::kSelect, mlir::sparse_tensor::kShlI, mlir::sparse_tensor::kShrS, mlir::sparse_tensor::kShrU, mlir::sparse_tensor::kSinC, mlir::sparse_tensor::kSinF, mlir::sparse_tensor::kSqrtC, mlir::sparse_tensor::kSqrtF, mlir::sparse_tensor::kSubC, mlir::sparse_tensor::kSubF, mlir::sparse_tensor::kSubI, mlir::sparse_tensor::kTanhC, mlir::sparse_tensor::kTanhF, mlir::sparse_tensor::kTensor, mlir::sparse_tensor::kTruncF, mlir::sparse_tensor::kTruncI, mlir::sparse_tensor::kUnary, and mlir::sparse_tensor::kXorI.
Referenced by isAdmissibleTensorExp().
lat()
LatPoint& mlir::sparse_tensor::Merger::lat (unsigned l) inline
Definition at line 344 of file Merger.h.
Referenced by mlir::sparse_tensor::CodegenEnv::lat().
latGT()
bool mlir::sparse_tensor::Merger::latGT (unsigned i, unsigned j) const
Returns true if Li > Lj.
Definition at line 379 of file Merger.cpp.
Referenced by genStmt(), optimizeSet(), and simplifyCond().
mapSet()
unsigned mlir::sparse_tensor::Merger::mapSet (Kind kind, unsigned s0, Value v = Value(), Operation * op = nullptr)
Maps the unary operator over the lattice set of the operand, i.e.
each lattice point on an expression E is simply copied over, but with OP E as new expression. Returns the index of the new set.
Definition at line 300 of file Merger.cpp.
References addExp(), addSet(), exp(), mlir::sparse_tensor::kAbsF, and mlir::sparse_tensor::kSelect.
Referenced by buildLattices(), takeCombi(), and takeDisj().
onlyDenseDiff()
bool mlir::sparse_tensor::Merger::onlyDenseDiff (unsigned i, unsigned j)
Returns true if Li and Lj only differ in dense.
Definition at line 392 of file Merger.cpp.
References hasAnySparse().
Referenced by optimizeSet().
optimizeSet()
unsigned mlir::sparse_tensor::Merger::optimizeSet (unsigned s0)
Optimizes the iteration lattice points in the given set.
This method should be called right before code generation to avoid generating redundant loops and conditions.
Definition at line 311 of file Merger.cpp.
References addSet(), mlir::sparse_tensor::kTensor, latGT(), onlyDenseDiff(), simplifyCond(), and tensor().
Referenced by genStmt().
set()
SmallVector<unsigned>& mlir::sparse_tensor::Merger::set (unsigned s) inline
Definition at line 345 of file Merger.h.
Referenced by mlir::sparse_tensor::CodegenEnv::set().
setDimAndDimLevelType()
void mlir::sparse_tensor::Merger::setDimAndDimLevelType (unsigned t, unsigned i, unsigned dim, DimLevelType dlt) inline
Sets the dimension and dimension level type of the tth tensor on ith loop.
Definition at line 316 of file Merger.h.
References mlir::sparse_tensor::isValidDLT().
Referenced by findAffine().
setHasSparseOut()
void mlir::sparse_tensor::Merger::setHasSparseOut (bool s) inline
Definition at line 337 of file Merger.h.
Referenced by mlir::sparse_tensor::CodegenEnv::startEmit().
simplifyCond()
BitVector mlir::sparse_tensor::Merger::simplifyCond (unsigned s0, unsigned p0)
Simplifies the conditions in a conjunction of a given lattice point within the given set using just two basic rules: (1) multiple dense conditions are reduced to single dense, and (2) a singleton sparse/dense is reduced to sparse/random access.
Definition at line 340 of file Merger.cpp.
References getDimLevelType(), hasAnySparse(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::isSingletonDLT(), and latGT().
Referenced by optimizeSet().
takeCombi()
unsigned mlir::sparse_tensor::Merger::takeCombi (Kind kind, unsigned s0, unsigned s1, Operation * orig, bool includeLeft, Kind ltrans, Operation * opleft, bool includeRight, Kind rtrans, Operation * opright)
Disjunctive merge of two lattice sets L0 and L1 with custom handling of the overlap, left, and right regions.
Any region may be left missing in the output. Returns the index of the new set.
Definition at line 279 of file Merger.cpp.
References mapSet(), and takeConj().
Referenced by buildLattices().
takeConj()
unsigned mlir::sparse_tensor::Merger::takeConj (Kind kind, unsigned s0, unsigned s1, Operation * op = nullptr)
Conjunctive merge of two lattice sets L0 and L1 is conjunction of cartesian product.
Returns the index of the new set.
Definition at line 252 of file Merger.cpp.
References addSet(), and conjLatPoint().
Referenced by buildLattices(), takeCombi(), and takeDisj().
takeDisj()
unsigned mlir::sparse_tensor::Merger::takeDisj (Kind kind, unsigned s0, unsigned s1, Operation * op = nullptr)
Disjunctive merge of two lattice sets L0 and L1 is (L0 /_op L1, L0, L1).
Returns the index of the new set.
Definition at line 260 of file Merger.cpp.
References mlir::sparse_tensor::kNegC, mlir::sparse_tensor::kNegF, mlir::sparse_tensor::kNegI, mlir::sparse_tensor::kSubC, mlir::sparse_tensor::kSubF, mlir::sparse_tensor::kSubI, mapSet(), and takeConj().
Referenced by buildLattices().
tensor()
unsigned mlir::sparse_tensor::Merger::tensor (unsigned b) const inline
Bit translation (get tensor ID).
Definition at line 240 of file Merger.h.
Referenced by dumpBits(), dumpExp(), expContainsTensor(), foreachTidDimPairInBits(), genIf(), getDimLevelType(), getDimNum(), isOutTensor(), and optimizeSet().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SparseTensor/Utils/Merger.h
lib/Dialect/SparseTensor/Utils/Merger.cpp