MLIR: lib/Dialect/GPU/TransformOps/GPUTransformOps.cpp File Reference
GPUTransformOps.cpp File Reference
#include "mlir/Dialect/GPU/TransformOps/GPUTransformOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/SCF/IR/DeviceMappingInterface.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/IR/TransformInterfaces.h"
#include "mlir/Dialect/Transform/IR/TransformUtils.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/Dialect/GPU/TransformOps/GPUTransformOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static DiagnosedSilenceableFailure checkAttributeType (ArrayRef< DeviceMappingAttrInterface > threadMappingAttributes, const std::optional< ArrayAttr > &foreachMapping, std::optional< TransformOpInterface > transformOp)
Check if given mapping attributes are one of the desired attributes.
static DiagnosedSilenceableFailure checkGpuLimits (TransformOpInterface transformOp, std::optional< int64_t > gridDimX, std::optional< int64_t > gridDimY, std::optional< int64_t > gridDimZ, std::optional< int64_t > blockDimX, std::optional< int64_t > blockDimY, std::optional< int64_t > blockDimZ)
Determines if the size of the kernel configuration is supported by the GPU architecture being used.
static DiagnosedSilenceableFailure createGpuLaunch (RewriterBase &rewriter, Location loc, TransformOpInterface transformOp, LaunchOp &launchOp, std::optional< int64_t > gridDimX=std::nullopt, std::optional< int64_t > gridDimY=std::nullopt, std::optional< int64_t > gridDimZ=std::nullopt, std::optional< int64_t > blockDimX=std::nullopt, std::optional< int64_t > blockDimY=std::nullopt, std::optional< int64_t > blockDimZ=std::nullopt)
Creates an empty-body gpu::LaunchOp using the provided kernel settings and put a terminator within.
static DiagnosedSilenceableFailure alterGpuLaunch (TrivialPatternRewriter &rewriter, LaunchOp gpuLaunch, TransformOpInterface transformOp, std::optional< int64_t > gridDimX=std::nullopt, std::optional< int64_t > gridDimY=std::nullopt, std::optional< int64_t > gridDimZ=std::nullopt, std::optional< int64_t > blockDimX=std::nullopt, std::optional< int64_t > blockDimY=std::nullopt, std::optional< int64_t > blockDimZ=std::nullopt)
Alter kernel configuration of the given kernel.
static void generateGpuBlockIds (RewriterBase &rewriter, scf::ForeachThreadOp foreachOp, SmallVectorImpl< Value > &blockOps)
This is a helper that is only used in rewriteTopLevelForeachThreadToGpuBlocks.
static DiagnosedSilenceableFailure rewriteOneForeachThreadToGpuThreads (RewriterBase &rewriter, scf::ForeachThreadOp foreachThreadOp, const SmallVectorImpl< int64_t > &globalBlockDims, bool syncAfterDistribute, std::optional< TransformOpInterface > transformOp, const ArrayRef< DeviceMappingAttrInterface > &threadMappingAttributes)
Searches scf.foreach_thread ops nested under target and maps each such op to GPU threads.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 593 of file GPUTransformOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
alterGpuLaunch()
static DiagnosedSilenceableFailure alterGpuLaunch (TrivialPatternRewriter & rewriter, LaunchOp gpuLaunch, TransformOpInterface transformOp, std::optional< int64_t > gridDimX = std::nullopt, std::optional< int64_t > gridDimY = std::nullopt, std::optional< int64_t > gridDimZ = std::nullopt, std::optional< int64_t > blockDimX = std::nullopt, std::optional< int64_t > blockDimY = std::nullopt, std::optional< int64_t > blockDimZ = std::nullopt) static
Alter kernel configuration of the given kernel.
Definition at line 127 of file GPUTransformOps.cpp.
References checkGpuLimits(), mlir::OpBuilder::create(), diag(), mlir::Value::getLoc(), mlir::OpBuilder::setInsertionPointAfterValue(), mlir::DiagnosedSilenceableFailure::success(), and mlir::gpu::KernelDim3::x.
checkAttributeType()
static DiagnosedSilenceableFailure checkAttributeType (ArrayRef< DeviceMappingAttrInterface > threadMappingAttributes, const std::optional< ArrayAttr > & foreachMapping, std::optional< TransformOpInterface > transformOp) static
Check if given mapping attributes are one of the desired attributes.
Definition at line 28 of file GPUTransformOps.cpp.
References mlir::DiagnosedSilenceableFailure::success().
Referenced by mlir::transform::gpu::mapNestedForeachToThreadsImpl().
checkGpuLimits()
static DiagnosedSilenceableFailure checkGpuLimits (TransformOpInterface transformOp, std::optional< int64_t > gridDimX, std::optional< int64_t > gridDimY, std::optional< int64_t > gridDimZ, std::optional< int64_t > blockDimX, std::optional< int64_t > blockDimY, std::optional< int64_t > blockDimZ) static
Determines if the size of the kernel configuration is supported by the GPU architecture being used.
It presently makes use of CUDA limitations, however that aspect may be enhanced for other GPUs.
Definition at line 55 of file GPUTransformOps.cpp.
References mlir::DiagnosedSilenceableFailure::success().
Referenced by alterGpuLaunch(), and createGpuLaunch().
createGpuLaunch()
static DiagnosedSilenceableFailure createGpuLaunch (RewriterBase & rewriter, Location loc, TransformOpInterface transformOp, LaunchOp & launchOp, std::optional< int64_t > gridDimX = std::nullopt, std::optional< int64_t > gridDimY = std::nullopt, std::optional< int64_t > gridDimZ = std::nullopt, std::optional< int64_t > blockDimX = std::nullopt, std::optional< int64_t > blockDimY = std::nullopt, std::optional< int64_t > blockDimZ = std::nullopt) static
Creates an empty-body gpu::LaunchOp using the provided kernel settings and put a terminator within.
Definition at line 93 of file GPUTransformOps.cpp.
References checkGpuLimits(), mlir::OpBuilder::create(), createConst(), diag(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::DiagnosedSilenceableFailure::success().
generateGpuBlockIds()
static void generateGpuBlockIds (RewriterBase & rewriter, scf::ForeachThreadOp foreachOp, SmallVectorImpl< Value > & blockOps) static
This is a helper that is only used in rewriteTopLevelForeachThreadToGpuBlocks.
It generates GPU dialects block_id.
Definition at line 279 of file GPUTransformOps.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIndexType(), and mlir::OpBuilder::setInsertionPoint().
rewriteOneForeachThreadToGpuThreads()
static DiagnosedSilenceableFailure rewriteOneForeachThreadToGpuThreads (RewriterBase & rewriter, scf::ForeachThreadOp foreachThreadOp, const SmallVectorImpl< int64_t > & globalBlockDims, bool syncAfterDistribute, std::optional< TransformOpInterface > transformOp, const ArrayRef< DeviceMappingAttrInterface > & threadMappingAttributes) static
Searches scf.foreach_thread ops nested under target and maps each such op to GPU threads.
Mapping is one-to-one and the induction variables of scf.foreach_thread are rewritten to gpu.thread_id according to the thread_dim_apping attribute. Sibling scf.foreach_thread are supported in which case, the union of the number of threads is computed and may result in predication. Dynamic, scf.foreach_thread trip counts are currently not supported. Dynamic block dim sizes are currently not supported.
Definition at line 370 of file GPUTransformOps.cpp.
References mlir::Block::begin(), mlir::OpBuilder::create(), mlir::emitDefiniteFailure(), mlir::RewriterBase::eraseOp(), mlir::Block::front(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexType(), mlir::Block::getOperations(), mlir::BlockAndValueMapping::lookup(), mlir::BlockAndValueMapping::map(), mlir::RewriterBase::replaceAllUsesWith(), mlir::DiagnosedSilenceableFailure::success(), and value.
Referenced by mlir::transform::gpu::mapNestedForeachToThreadsImpl().