MLIR: lib/Dialect/Linalg/TransformOps/LinalgTransformOps.cpp File Reference
LinalgTransformOps.cpp File Reference
#include "mlir/Dialect/Linalg/TransformOps/LinalgTransformOps.h"
#include "mlir/AsmParser/AsmParser.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/Dialect/SCF/Transforms/TileUsingInterface.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/IR/TransformInterfaces.h"
#include "mlir/Dialect/Transform/IR/TransformUtils.h"
#include "mlir/Dialect/Transform/Utils/Utils.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Interfaces/TilingInterface.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/Debug.h"
#include "mlir/Dialect/Linalg/TransformOps/LinalgTransformOps.cpp.inc"
#include "mlir/Dialect/Linalg/TransformOps/LinalgTransformOpsEnums.cpp.inc"
Macros
#define DEBUG_TYPE "linalg-transforms"
#define DOWNSCALE(trans)
#define DOWNSCALE_CALL(a, b) DownscaleSizeOneWindowed2DConvolution<a, b>
#define DOWNSCALE_NORMAL(a, b) DOWNSCALE(DOWNSCALE_CALL(a, b))
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
template<typename PatternTy , typename... Args>
static FailureOr< LinalgOp > tryApply (Operation *operation, Args &&...args)
Attempts to apply the pattern specified as template argument to the given operation.
static LogicalResult applyTilingToAll (Operation *transformOp, ArrayRef< Operation * > payloadOps, unsigned numLoops, transform::TransformResults &transformResults, function_ref< FailureOr< scf::SCFTileAndFuseResult >(TilingInterface)> applyFn)
Apply a tiling transformation to all payload ops and store both the tiled operation as well as the created tile loops.
static ParseResult parseTileLikeOp (OpAsmParser &parser, OperationState &result, StringRef sizesAttrName)
Parse a tiling-like operation that returns the tiled op as well as the created tile loops.
static Operation * tileAndFuseFirstExtractUse (RewriterBase &rewriter, Diagnostic &diag, Operation *producerOp, Operation *containingOp)
Find the first "extract" user of producerOp and tile it right before its use.
static Operation * tileAndFuseFirstExtractUseThroughContainingOpBlockArgument (RewriterBase &rewriter, Diagnostic &diag, Operation *producerOp, Operation *containingOp)
First, find the first "scf::ForeachThreadOp" user of producerOp and ensure it is exactly the containingOp, otherwise bail.
static Operation * cloneAndFuseFirstUse (RewriterBase &rewriter, Diagnostic &diag, Operation *producerOp, Operation *containingOp)
ParseResult parseOptionalInterchange (OpAsmParser &parser, OperationState &result)
void printOptionalInterchange (OpAsmPrinter &p, ArrayRef< int64_t > interchangeVals)
static DiagnosedSilenceableFailure unpackPDLOperations (transform::TransformState &state, TransformOpInterface transformOp, SmallVector< OpFoldResult > &result, ArrayRef< OpFoldResult > ofrs)
Assuming that ofr is an index attr or a transform dialect handle mapped to exactly one op with one index result, return that value.
static DiagnosedSilenceableFailure unpackPDLOperations (transform::TransformState &state, TransformOpInterface transformOp, SmallVector< OpFoldResult > &result, Value packedHandle)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-transforms"
Definition at line 36 of file LinalgTransformOps.cpp.
DOWNSCALE
#define DOWNSCALE (trans)
Value:
  {                                                                            \
    FailureOr<LinalgOp> res = tryApply<trans>(target);                         \
    if (succeeded(res)) {                                                      \
      results.push_back(*res);                                                 \
      return DiagnosedSilenceableFailure::success();                           \
    }                                                                          \
  }
DOWNSCALE_CALL
#define DOWNSCALE_CALL (a, b) DownscaleSizeOneWindowed2DConvolution<a, b>
DOWNSCALE_NORMAL
#define DOWNSCALE_NORMAL (a, b) DOWNSCALE(DOWNSCALE_CALL(a, b))
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2101 of file LinalgTransformOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
applyTilingToAll()
static LogicalResult applyTilingToAll (Operation * transformOp, ArrayRef< Operation * > payloadOps, unsigned numLoops, transform::TransformResults & transformResults, function_ref< FailureOr< scf::SCFTileAndFuseResult >(TilingInterface)> applyFn) static
Apply a tiling transformation to all payload ops and store both the tiled operation as well as the created tile loops.
Definition at line 104 of file LinalgTransformOps.cpp.
References mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Operation::getOpResult(), mlir::RewriterBase::replaceOp(), mlir::transform::TransformResults::set(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
cloneAndFuseFirstUse()
static Operation* cloneAndFuseFirstUse (RewriterBase & rewriter, Diagnostic & diag, Operation * producerOp, Operation * containingOp) static
Definition at line 425 of file LinalgTransformOps.cpp.
References mlir::Value::cast(), mlir::OpBuilder::clone(), diag(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Operation::getLoc(), mlir::Operation::getOpResults(), mlir::detail::IROperandBase::getOwner(), mlir::Operation::isProperAncestor(), mlir::OpBuilder::setInsertionPoint(), and mlir::RewriterBase::updateRootInPlace().
parseOptionalInterchange()
ParseResult parseOptionalInterchange (OpAsmParser & parser, OperationState & result)
Definition at line 1438 of file LinalgTransformOps.cpp.
References mlir::OperationState::addAttribute(), mlir::AsmParser::emitError(), mlir::failed(), mlir::AsmParser::getNameLoc(), mlir::detail::DenseArrayAttrImpl< T >::parse(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseOptionalLBrace(), mlir::AsmParser::parseRBrace(), mlir::succeeded(), and mlir::success().
parseTileLikeOp()
static ParseResult parseTileLikeOp (OpAsmParser & parser, OperationState & result, StringRef sizesAttrName) static
Parse a tiling-like operation that returns the tiled op as well as the created tile loops.
The function counts the non-zero tile sizes to compute the number of results.
Definition at line 161 of file LinalgTransformOps.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Attribute::dyn_cast(), mlir::AsmParser::emitError(), mlir::extractFromI64ArrayAttr(), mlir::failure(), mlir::NamedAttrList::get(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getType(), mlir::OperationState::operands, mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
printOptionalInterchange()
void printOptionalInterchange (OpAsmPrinter & p, ArrayRef< int64_t > interchangeVals)
Definition at line 1453 of file LinalgTransformOps.cpp.
tileAndFuseFirstExtractUse()
static Operation* tileAndFuseFirstExtractUse (RewriterBase & rewriter, Diagnostic & diag, Operation * producerOp, Operation * containingOp) static
Find the first "extract" user of producerOp and tile it right before its use.
The tiled op is fused under the containingOp. Return this fused op on success or nullptr if anything fails.
Definition at line 251 of file LinalgTransformOps.cpp.
References mlir::Type::cast(), diag(), mlir::failed(), mlir::Operation::getLoc(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPoint(), and mlir::succeeded().
tileAndFuseFirstExtractUseThroughContainingOpBlockArgument()
static Operation* tileAndFuseFirstExtractUseThroughContainingOpBlockArgument (RewriterBase & rewriter, Diagnostic & diag, Operation * producerOp, Operation * containingOp) static
First, find the first "scf::ForeachThreadOp" user of producerOp and ensure it is exactly the containingOp, otherwise bail.
Then, find the first "extract" user of the tied block argument and tile it right before its "extract" use. The tiled op is fused under the containingOp. Return this fused op on success or nullptr if anything fails.
Definition at line 317 of file LinalgTransformOps.cpp.
References mlir::Type::cast(), mlir::Value::cast(), mlir::OpBuilder::clone(), diag(), mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Operation::getLoc(), mlir::OpOperand::getOperandNumber(), mlir::tensor::getOrCreateDestinations(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::Value::getUsers(), mlir::BlockAndValueMapping::map(), mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPoint(), mlir::Operation::setOperand(), mlir::succeeded(), and mlir::RewriterBase::updateRootInPlace().
tryApply()
template<typename PatternTy , typename... Args> static FailureOr<LinalgOp> tryApply (Operation * operation, Args &&... args) static
Attempts to apply the pattern specified as template argument to the given operation.
The pattern is expected to have a returningMatchAndRewrite function that returns the "main" result or failure. Returns failure if the pattern failed to apply. Extra arguments are forwarded to the pattern constructor.
Definition at line 44 of file LinalgTransformOps.cpp.
References mlir::failed(), mlir::failure(), mlir::Operation::getContext(), and mlir::OpBuilder::setInsertionPoint().
unpackPDLOperations() [1/2]
static DiagnosedSilenceableFailure unpackPDLOperations (transform::TransformState & state, TransformOpInterface transformOp, SmallVector< OpFoldResult > & result, ArrayRef< OpFoldResult > ofrs) static
Assuming that ofr is an index attr or a transform dialect handle mapped to exactly one op with one index result, return that value.
Definition at line 1582 of file LinalgTransformOps.cpp.
References diag(), mlir::Operation::getLoc(), mlir::Value::getLoc(), mlir::Operation::getNumResults(), mlir::transform::TransformState::getPayloadOps(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::Attribute::isa(), mlir::Type::isIndex(), and mlir::DiagnosedSilenceableFailure::success().
unpackPDLOperations() [2/2]
static DiagnosedSilenceableFailure unpackPDLOperations (transform::TransformState & state, TransformOpInterface transformOp, SmallVector< OpFoldResult > & result, Value packedHandle) static
Definition at line 1623 of file LinalgTransformOps.cpp.
References diag(), mlir::Operation::getLoc(), mlir::Operation::getNumResults(), mlir::transform::TransformState::getPayloadOps(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::Type::isIndex(), and mlir::DiagnosedSilenceableFailure::success().