MLIR: lib/Dialect/SparseTensor/Transforms/LoopEmitter.cpp File Reference
LoopEmitter.cpp File Reference
#include "LoopEmitter.h"
#include "CodegenUtils.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
Functions
static Value genIndexLoad (OpBuilder &builder, Location loc, Value ptr, Value s)
Generates a pointer/index load from the sparse storage scheme.
Function Documentation
genIndexLoad()
static Value genIndexLoad (OpBuilder & builder, Location loc, Value ptr, Value s) static
Generates a pointer/index load from the sparse storage scheme.
Narrower data types need to be zero extended before casting the value into the index type used for looping and indexing.
Definition at line 29 of file LoopEmitter.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64Type(), mlir::Builder::getIndexType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::sparse_tensor::LoopEmitter::enterCoIterationOverTensorsAtDims(), mlir::sparse_tensor::LoopEmitter::enterFilterLoopOverTensorAtDim(), and mlir::sparse_tensor::LoopEmitter::enterLoopOverTensorAtDim().