MLIR: lib/Dialect/Bufferization/Transforms/OneShotAnalysis.cpp File Reference
OneShotAnalysis.cpp File Reference
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include <random>
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/Transforms.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SetVector.h"
Macros
#define DEBUG_TYPE "one-shot-analysis"
Functions
static bool isaTensor (Type t)
static void setInPlaceOpOperand (OpOperand &opOperand, bool inPlace)
Mark whether OpOperand will be bufferized inplace.
static bool isInplaceMemoryWrite (OpOperand &opOperand, const BufferizationAliasInfo &aliasInfo, const AnalysisState &state)
Return true if opOperand has been decided to bufferize in-place.
static bool happensBefore (Operation *a, Operation *b, const DominanceInfo &domInfo)
Return true if a happens before b, i.e., a or one of its ancestors properly dominates b and b is not inside a.
static Region * getEnclosingRepetitiveRegion (Operation *op, const BufferizationOptions &options)
static Region * getEnclosingRepetitiveRegion (Value value, const BufferizationOptions &options)
static bool isMemoryWrite (Value value, const AnalysisState &state)
Return true if the given tensor value is a memory write.
bool canUseOpDominance (const DenseSet< OpOperand * > &usesRead, const DenseSet< OpOperand * > &usesWrite, const AnalysisState &state)
Return true if op dominance can be used to rule out read-after-write conflicts wrt.
static void annotateConflict (OpOperand *uRead, OpOperand *uConflictingWrite, Value lastWrite)
Annotate IR with details about the detected RaW conflict.
static bool hasReadAfterWriteInterference (const DenseSet< OpOperand * > &usesRead, const DenseSet< OpOperand * > &usesWrite, const DominanceInfo &domInfo, AnalysisState &state, const BufferizationAliasInfo &aliasInfo)
Given sets of uses and writes, return true if there is a RaW conflict under the assumption that all given reads/writes alias the same buffer and that all given writes bufferize inplace.
static void getAliasingInplaceWrites (DenseSet< OpOperand * > &res, Value root, const BufferizationAliasInfo &aliasInfo, const AnalysisState &state)
static void getAliasingReads (DenseSet< OpOperand * > &res, Value root, const BufferizationAliasInfo &aliasInfo, const AnalysisState &state)
static bool wouldCreateReadAfterWriteInterference (OpOperand &operand, const DominanceInfo &domInfo, AnalysisState &state, const BufferizationAliasInfo &aliasInfo, bool checkConsistencyOnly=false)
Return true if bufferizing operand inplace would create a conflict.
static void annotateNonWritableTensor (Value value)
Annotate IR with details about the detected non-writability conflict.
static bool hasPrecedingAliasingNonWritableTensor (Value value, OpOperand *currentOpOperand, const BufferizationAliasInfo &aliasInfo, const OneShotAnalysisState &state)
Check the reverse SSA use-def chain (following aliasing OpOperands) for non-writable tensor values.
static bool wouldCreateWriteToNonWritableBuffer (OpOperand &operand, const BufferizationAliasInfo &aliasInfo, OneShotAnalysisState &state, bool checkConsistencyOnly=false)
Return true if bufferizing operand inplace would create a write to a non-writable buffer.
static LogicalResult bufferizableInPlaceAnalysisImpl (OpOperand &operand, BufferizationAliasInfo &aliasInfo, OneShotAnalysisState &state, const DominanceInfo &domInfo)
Determine if operand can be bufferized in-place.
static LogicalResult inPlaceAnalysis (SmallVector< Operation * > &ops, BufferizationAliasInfo &aliasInfo, OneShotAnalysisState &state, const DominanceInfo &domInfo, unsigned analysisFuzzerSeed=0)
Analyze the ops to determine which OpOperands are inplaceable.
static bool hasTensorSemantics (Operation *op)
Return true if the given op has a tensor result or a tensor operand.
static LogicalResult inPlaceAnalysis (Operation *op, BufferizationAliasInfo &aliasInfo, OneShotAnalysisState &state, const DominanceInfo &domInfo, unsigned analysisFuzzerSeed=0)
Analyze all ops that are contained in op.
static void equivalenceAnalysis (SmallVector< Operation * > &ops, BufferizationAliasInfo &aliasInfo, AnalysisState &state)
Analyze equivalence of tied OpResult/OpOperand pairs of the given ops.
static void equivalenceAnalysis (Operation *op, BufferizationAliasInfo &aliasInfo, AnalysisState &state)
Analyze equivalence of tied OpResult/OpOperand pairs of all ops contained in op.
static LogicalResult checkAliasInfoConsistency (Operation *op, const DominanceInfo &domInfo, AnalysisState &state, const BufferizationAliasInfo &aliasInfo)
Assert that the current bufferization decisions are consistent.
static void annotateOpsWithBufferizationMarkers (Operation *op, const BufferizationAliasInfo &aliasInfo, const BufferizationOptions &options)
Annotate the IR with the result of the analysis. For testing/debugging only.
static LogicalResult assertNoAllocsReturned (Operation *op, const BufferizationOptions &options, BufferizationAliasInfo &aliasInfo)
Assert that every allocation can be deallocated in the same block.
Variables
constexpr StringLiteral kInPlaceOperandsAttrName = "__inplace_operands_attr__"
Attribute marker to specify op operands that bufferize in-place.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "one-shot-analysis"
Definition at line 63 of file OneShotAnalysis.cpp.
Function Documentation
annotateConflict()
static void annotateConflict (OpOperand * uRead, OpOperand * uConflictingWrite, Value lastWrite) static
Annotate IR with details about the detected RaW conflict.
Definition at line 513 of file OneShotAnalysis.cpp.
References mlir::Value::cast(), mlir::Value::dyn_cast(), mlir::Operation::getContext(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::Builder::getUnitAttr(), and mlir::Operation::setAttr().
Referenced by hasReadAfterWriteInterference().
annotateNonWritableTensor()
static void annotateNonWritableTensor (Value value) static
Annotate IR with details about the detected non-writability conflict.
Definition at line 807 of file OneShotAnalysis.cpp.
References mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::Builder::getUnitAttr(), mlir::Operation::setAttr(), and value.
Referenced by hasPrecedingAliasingNonWritableTensor().
annotateOpsWithBufferizationMarkers()
static void annotateOpsWithBufferizationMarkers (Operation * op, const BufferizationAliasInfo & aliasInfo, const BufferizationOptions & options) static
Annotate the IR with the result of the analysis. For testing/debugging only.
Definition at line 1072 of file OneShotAnalysis.cpp.
References mlir::bufferization::BufferizationAliasInfo::isInPlace(), options, setInPlaceOpOperand(), and mlir::Operation::walk().
Referenced by mlir::bufferization::analyzeOp().
assertNoAllocsReturned()
static LogicalResult assertNoAllocsReturned (Operation * op, const BufferizationOptions & options, BufferizationAliasInfo & aliasInfo) static
Assert that every allocation can be deallocated in the same block.
I.e., every value that is returned or yielded from a block is:
guaranteed to be aliasing a bbArg of that block or a parent block, or
guaranteed to be aliasing an OpResult of a op in a parent block.
In that case, buffer deallocation is simple: Every allocated buffer can be deallocated in the same block. Otherwise, the buffer deallocation pass must be run.
Note: The current implementation checks for equivalent values instead of aliasing values, which is stricter than needed. We can currently not check for aliasing values because the analysis is a maybe-alias analysis and we need a must-alias analysis here.
Example:
%0 = "some_op" : tensor<?xf32>
%1 = scf.if %c -> (tensor<?xf32>) {
  scf.yield %0 : tensor<?xf32>
} else {
  %t = linalg.alloc_tensor : tensor<?xf32>
  scf.yield %t : tensor<?xf32>
}
In the above example, the second scf.yield op is problematic because the yielded value t is defined in the same block as the scf.yield op and and bufferizes to a new allocation.
Definition at line 1114 of file OneShotAnalysis.cpp.
References mlir::Operation::emitError(), mlir::Operation::getOpOperands(), mlir::isRegionReturnLike(), options, mlir::success(), and mlir::Operation::walk().
Referenced by mlir::bufferization::analyzeOp().
bufferizableInPlaceAnalysisImpl()
static LogicalResult bufferizableInPlaceAnalysisImpl (OpOperand & operand, BufferizationAliasInfo & aliasInfo, OneShotAnalysisState & state, const DominanceInfo & domInfo) static
Determine if operand can be bufferized in-place.
Definition at line 890 of file OneShotAnalysis.cpp.
References mlir::bufferization::BufferizationAliasInfo::bufferizeInPlace(), mlir::bufferization::BufferizationAliasInfo::bufferizeOutOfPlace(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), mlir::success(), wouldCreateReadAfterWriteInterference(), and wouldCreateWriteToNonWritableBuffer().
Referenced by inPlaceAnalysis().
canUseOpDominance()
bool canUseOpDominance (const DenseSet< OpOperand * > & usesRead, const DenseSet< OpOperand * > & usesWrite, const AnalysisState & state)
Return true if op dominance can be used to rule out read-after-write conflicts wrt.
the given reads and writes.
Op dominance can often be used to rule out potential conflicts such as "read" happens before "write". E.g., the following IR is not a RaW conflict because the the read happens before the write.
%0 = ... : tensor<?xf32> "reading_op"(%0) : tensor<?xf32> %1 = "writing_op"(%0) : tensor<?xf32> -> tensor<?xf32>
This is no longer true inside loops (or repetitive regions). In such cases, there may not be a meaningful happensBefore relationship because ops could be executed multiple times. E.g.:
%0 = ... : tensor<?xf32> scf.for ... { "reading_op"(%0) : tensor<?xf32> %1 = "writing_op"(%0) : tensor<?xf32> -> tensor<?xf32> ... }
In the above example, reading_op happens before writing_op according to op dominance. However, both ops may happen multiple times; in particular, the second execution of reading_op happens after the first execution of writing_op. This is problematic because the tensor %0 they operate on (i.e., the "definition") is defined outside of the loop.
Counter example:
scf.for ... { %0 = ... : tensor<?xf32> "reading_op"(%0) : tensor<?xf32> %1 = "writing_op"(%0) : tensor<?xf32> -> tensor<?xf32> ... }
In this example, the definition %0 is in the same repetitive region as "writing_op", so op dominance can be used to compute the happensBefore relationship.
Whether op dominance can be used or not is decided as follows: Find the closest enclosing repetitive region of all buffer writes wrt. the given tensor reads and writes. (The given sets of reads and writes contain the entire alias set.) In case of a read, we look at the op that defines the read value. In case of a write, we look at the op that is writing. If all of those ops are in the same closest enclosing repetitive region (nullptr in case of "no repetitive region" found at all), then op dominance can be used. Otherwise, it cannot be used.
Example: The common enclosing repetitive region is the scf.for loop. Op dominance can be used. scf.for ... { %0 = tensor.generate "read"(%0) }
Example: The common enclosing repetitive region is nullptr: There is no repetitive region around the tensor.generate. Op dominance can be used. %0 = tensor.generate scf.for ... { "read"(%0) }
Example: The common enclosing repetitive regions of tensor.generate and "write" differ. Op dominance cannot be used. %0 = tensor.generate scf.for ... { "read"(%0) "write"(%0) }
Example: The common enclosing repetitive regions of tensor.generate and "write" differ, but there is no read of %0, so op dominance can be used. %0 = tensor.generate scf.for ... { "write"(%0) }
Note: iter_args of loops are not aliases of their respective block arguments, so op domanice can be used when analyzing ops that operate on them.
Definition at line 478 of file OneShotAnalysis.cpp.
References mlir::getEnclosingRepetitiveRegion(), isMemoryWrite(), and options.
Referenced by hasReadAfterWriteInterference().
checkAliasInfoConsistency()
static LogicalResult checkAliasInfoConsistency (Operation * op, const DominanceInfo & domInfo, AnalysisState & state, const BufferizationAliasInfo & aliasInfo) static
Assert that the current bufferization decisions are consistent.
Definition at line 1033 of file OneShotAnalysis.cpp.
References mlir::Operation::getOpOperands(), options, and mlir::Operation::walk().
Referenced by mlir::bufferization::analyzeOp().
equivalenceAnalysis() [1/2]
static void equivalenceAnalysis (Operation * op, BufferizationAliasInfo & aliasInfo, AnalysisState & state) static
Analyze equivalence of tied OpResult/OpOperand pairs of all ops contained in op.
Definition at line 1016 of file OneShotAnalysis.cpp.
References equivalenceAnalysis(), mlir::Operation::getResultTypes(), isaTensor(), and mlir::Operation::walk().
equivalenceAnalysis() [2/2]
static void equivalenceAnalysis (SmallVector< Operation * > & ops, BufferizationAliasInfo & aliasInfo, AnalysisState & state) static
Analyze equivalence of tied OpResult/OpOperand pairs of the given ops.
Definition at line 999 of file OneShotAnalysis.cpp.
References mlir::bufferization::BufferizationAliasInfo::unionEquivalenceClasses().
Referenced by mlir::bufferization::analyzeOp(), and equivalenceAnalysis().
getAliasingInplaceWrites()
static void getAliasingInplaceWrites (DenseSet< OpOperand * > & res, Value root, const BufferizationAliasInfo & aliasInfo, const AnalysisState & state) static
Definition at line 710 of file OneShotAnalysis.cpp.
References mlir::bufferization::BufferizationAliasInfo::applyOnAliases(), mlir::Value::getUses(), and isInplaceMemoryWrite().
Referenced by wouldCreateReadAfterWriteInterference(), and wouldCreateWriteToNonWritableBuffer().
getAliasingReads()
static void getAliasingReads (DenseSet< OpOperand * > & res, Value root, const BufferizationAliasInfo & aliasInfo, const AnalysisState & state) static
Definition at line 722 of file OneShotAnalysis.cpp.
References mlir::bufferization::BufferizationAliasInfo::applyOnAliases(), and mlir::Value::getUses().
Referenced by wouldCreateReadAfterWriteInterference().
getEnclosingRepetitiveRegion() [1/2]
static Region* getEnclosingRepetitiveRegion (Operation * op, const BufferizationOptions & options) static
Definition at line 359 of file OneShotAnalysis.cpp.
References mlir::Operation::getParentOp(), mlir::Operation::getParentRegion(), and options.
getEnclosingRepetitiveRegion() [2/2]
static Region* getEnclosingRepetitiveRegion (Value value, const BufferizationOptions & options) static
Definition at line 371 of file OneShotAnalysis.cpp.
References mlir::Region::getParentOp(), mlir::Operation::getParentRegion(), mlir::Region::getRegionNumber(), options, and value.
happensBefore()
static bool happensBefore (Operation * a, Operation * b, const DominanceInfo & domInfo) static
Return true if a happens before b, i.e., a or one of its ancestors properly dominates b and b is not inside a.
Definition at line 345 of file OneShotAnalysis.cpp.
References mlir::Operation::getParentOp(), mlir::Operation::isProperAncestor(), and mlir::DominanceInfo::properlyDominates().
Referenced by hasReadAfterWriteInterference().
hasPrecedingAliasingNonWritableTensor()
static bool hasPrecedingAliasingNonWritableTensor (Value value, OpOperand * currentOpOperand, const BufferizationAliasInfo & aliasInfo, const OneShotAnalysisState & state) static
Check the reverse SSA use-def chain (following aliasing OpOperands) for non-writable tensor values.
Stop searching when an out-of-place bufferized OpOperand was found (or when the OpOperand was not bufferized yet). currentOpOperand is assumed to be in-place, even if that decision was not materialized in aliasInfo yet.
Definition at line 829 of file OneShotAnalysis.cpp.
References annotateNonWritableTensor(), mlir::Value::dyn_cast(), mlir::bufferization::AnalysisState::getAliasingOpOperand(), mlir::bufferization::OneShotAnalysisState::getOptions(), mlir::bufferization::BufferizationAliasInfo::isInPlace(), mlir::bufferization::OneShotAnalysisState::isWritable(), mlir::bufferization::BufferizationOptions::printConflicts, and value.
Referenced by wouldCreateWriteToNonWritableBuffer().
hasReadAfterWriteInterference()
static bool hasReadAfterWriteInterference (const DenseSet< OpOperand * > & usesRead, const DenseSet< OpOperand * > & usesWrite, const DominanceInfo & domInfo, AnalysisState & state, const BufferizationAliasInfo & aliasInfo) static
Given sets of uses and writes, return true if there is a RaW conflict under the assumption that all given reads/writes alias the same buffer and that all given writes bufferize inplace.
A conflict is: According to SSA use-def chains, a read R is supposed to read the result of a write W1. But because of bufferization decisions, R actually reads another write W2.
Definition at line 552 of file OneShotAnalysis.cpp.
References annotateConflict(), canUseOpDominance(), happensBefore(), mlir::insideMutuallyExclusiveRegions(), and options.
Referenced by wouldCreateReadAfterWriteInterference().
hasTensorSemantics()
static bool hasTensorSemantics (Operation * op) static
Return true if the given op has a tensor result or a tensor operand.
Definition at line 974 of file OneShotAnalysis.cpp.
References mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), and isaTensor().
Referenced by inPlaceAnalysis().
inPlaceAnalysis() [1/2]
static LogicalResult inPlaceAnalysis (Operation * op, BufferizationAliasInfo & aliasInfo, OneShotAnalysisState & state, const DominanceInfo & domInfo, unsigned analysisFuzzerSeed = 0) static
Analyze all ops that are contained in op.
Definition at line 981 of file OneShotAnalysis.cpp.
References hasTensorSemantics(), inPlaceAnalysis(), and mlir::Operation::walk().
inPlaceAnalysis() [2/2]
static LogicalResult inPlaceAnalysis (SmallVector< Operation * > & ops, BufferizationAliasInfo & aliasInfo, OneShotAnalysisState & state, const DominanceInfo & domInfo, unsigned analysisFuzzerSeed = 0) static
Analyze the ops to determine which OpOperands are inplaceable.
Walk ops in reverse and bufferize ops greedily. This is a good starter heuristic.
Even if an op does not read or write, it may still create an alias when bufferized in-place. An example of such ops is tensor.extract_slice.
Rationale for bufferizing %1 = tensor.extract_slice %0[...] inplace:
When bufferized out of place, an ExtractSliceOp lowers to alloc + copy. This cannot change the flow of information for either the source or the result buffers.
When bufferized inplace, an ExtractSliceOp does not by itself create any read or write from memory. Instead, it has the effect of merging the alias sets of the source and the result buffers.
An analysis is required to ensure inplace bufferization would not result in RaW dependence violations.
Definition at line 930 of file OneShotAnalysis.cpp.
References mlir::bufferization::OneShotBufferizationOptions::analysisHeuristic, mlir::bufferization::analyzeOp(), bufferizableInPlaceAnalysisImpl(), mlir::bufferization::BufferizationOptions::dynCastBufferizableOp(), mlir::failed(), mlir::failure(), mlir::bufferization::OneShotAnalysisState::getOptions(), and mlir::success().
Referenced by mlir::bufferization::analyzeOp(), and inPlaceAnalysis().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 68 of file OneShotAnalysis.cpp.
References mlir::Type::isa().
Referenced by equivalenceAnalysis(), and hasTensorSemantics().
isInplaceMemoryWrite()
static bool isInplaceMemoryWrite (OpOperand & opOperand, const BufferizationAliasInfo & aliasInfo, const AnalysisState & state) static
Return true if opOperand has been decided to bufferize in-place.
Definition at line 333 of file OneShotAnalysis.cpp.
References mlir::bufferization::BufferizationAliasInfo::isInPlace().
Referenced by getAliasingInplaceWrites().
isMemoryWrite()
static bool isMemoryWrite (Value value, const AnalysisState & state) static
Return true if the given tensor value is a memory write.
Most values are tensor writes, but ops that define a tensor SSA value without specifying its contents (e.g., alloc_tensor) are not.
Definition at line 386 of file OneShotAnalysis.cpp.
References value.
Referenced by canUseOpDominance().
setInPlaceOpOperand()
static void setInPlaceOpOperand (OpOperand & opOperand, bool inPlace) static
Mark whether OpOperand will be bufferized inplace.
Definition at line 82 of file OneShotAnalysis.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Operation::getAttr(), mlir::Operation::getNumOperands(), mlir::OpOperand::getOperandNumber(), mlir::Operation::getOpOperands(), mlir::detail::IROperandBase::getOwner(), mlir::Value::getType(), mlir::Type::isa(), kInPlaceOperandsAttrName, and mlir::Operation::setAttr().
Referenced by annotateOpsWithBufferizationMarkers().
wouldCreateReadAfterWriteInterference()
static bool wouldCreateReadAfterWriteInterference (OpOperand & operand, const DominanceInfo & domInfo, AnalysisState & state, const BufferizationAliasInfo & aliasInfo, bool checkConsistencyOnly = false) static
Return true if bufferizing operand inplace would create a conflict.
A read R and a write W of the same alias set is a conflict if inplace bufferization of W changes the value read by R to a value different from the one that would be expected by tracing back R's origin through SSA use-def chains. A conflict can only be introduced by a new alias and/or an inplace bufferization decision.
Example: %0 = tensor.extract_slice t[...][...][1, 1] {inplace?} %1 = vector.transfer_write v1, t {inplace} : vector<5xf32>, tensor<?xf32> e = tensor.extract_slice %1 %2 = vector.transfer_write v2, %0 {inplace} : vector<6xf32>, tensor<?xf32> %3 = vector.transfer_read e, cst : tensor<?xf32>, vector<7xf32>
In the above example, the two TransferWriteOps have already been decided to bufferize inplace. Bufferizing the ExtractSliceOp inplace would create a conflict because:
According to SSA use-def chains, we expect to read the result of %1.
However, adding an alias {%0, t} would mean that the second TransferWriteOp overwrites the first one. Therefore, the TransferReadOp would no longer be reading the result of %1.
If checkConsistencyOnly is true, this function checks if there is a read-after-write conflict without bufferizing operand inplace. This would indicate a problem with the current inplace bufferization decisions.
Note: If checkConsistencyOnly, this function may be called with a null OpResult. In that case, only the consistency of bufferization decisions involving aliases of the given OpOperand are checked.
Definition at line 787 of file OneShotAnalysis.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), getAliasingInplaceWrites(), getAliasingReads(), and hasReadAfterWriteInterference().
Referenced by bufferizableInPlaceAnalysisImpl().
wouldCreateWriteToNonWritableBuffer()
static bool wouldCreateWriteToNonWritableBuffer (OpOperand & operand, const BufferizationAliasInfo & aliasInfo, OneShotAnalysisState & state, bool checkConsistencyOnly = false) static
Return true if bufferizing operand inplace would create a write to a non-writable buffer.
Definition at line 859 of file OneShotAnalysis.cpp.
References mlir::bufferization::AnalysisState::bufferizesToMemoryWrite(), mlir::IROperand< DerivedT, IRValueT >::get(), getAliasingInplaceWrites(), mlir::bufferization::AnalysisState::getAliasingOpResult(), and hasPrecedingAliasingNonWritableTensor().
Referenced by bufferizableInPlaceAnalysisImpl().
Variable Documentation
kInPlaceOperandsAttrName
constexpr StringLiteral kInPlaceOperandsAttrName = "__inplace_operands_attr__" constexpr
Attribute marker to specify op operands that bufferize in-place.
Definition at line 79 of file OneShotAnalysis.cpp.
Referenced by setInPlaceOpOperand().