MLIR: lib/Dialect/SCF/Transforms/ParallelLoopFusion.cpp File Reference
ParallelLoopFusion.cpp File Reference
#include "mlir/Dialect/SCF/Transforms/Passes.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/Transforms/Transforms.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Dialect/SCF/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_SCFPARALLELLOOPFUSION
Functions
static bool hasNestedParallelOp (ParallelOp ploop)
Verify there are no nested ParallelOps.
static bool equalIterationSpaces (ParallelOp firstPloop, ParallelOp secondPloop)
Verify equal iteration spaces.
static bool haveNoReadsAfterWriteExceptSameIndex (ParallelOp firstPloop, ParallelOp secondPloop, const BlockAndValueMapping &firstToSecondPloopIndices)
Checks if the parallel loops have mixed access to the same buffers.
static LogicalResult verifyDependencies (ParallelOp firstPloop, ParallelOp secondPloop, const BlockAndValueMapping &firstToSecondPloopIndices)
Analyzes dependencies in the most primitive way by checking simple read and write patterns.
static bool isFusionLegal (ParallelOp firstPloop, ParallelOp secondPloop, const BlockAndValueMapping &firstToSecondPloopIndices)
static void fuseIfLegal (ParallelOp firstPloop, ParallelOp secondPloop, OpBuilder b)
Prepends operations of firstPloop's body into secondPloop's body.
Macro Definition Documentation
GEN_PASS_DEF_SCFPARALLELLOOPFUSION
#define GEN_PASS_DEF_SCFPARALLELLOOPFUSION
Definition at line 24 of file ParallelLoopFusion.cpp.
Function Documentation
equalIterationSpaces()
static bool equalIterationSpaces (ParallelOp firstPloop, ParallelOp secondPloop) static
Verify equal iteration spaces.
Definition at line 39 of file ParallelLoopFusion.cpp.
Referenced by isFusionLegal().
fuseIfLegal()
static void fuseIfLegal (ParallelOp firstPloop, ParallelOp secondPloop, OpBuilder b) static
Prepends operations of firstPloop's body into secondPloop's body.
Definition at line 124 of file ParallelLoopFusion.cpp.
References mlir::OpBuilder::clone(), mlir::Operation::erase(), isFusionLegal(), mlir::BlockAndValueMapping::map(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by mlir::scf::naivelyFuseParallelOps().
hasNestedParallelOp()
static bool hasNestedParallelOp (ParallelOp ploop) static
Verify there are no nested ParallelOps.
Definition at line 32 of file ParallelLoopFusion.cpp.
References mlir::WalkResult::interrupt().
Referenced by isFusionLegal().
haveNoReadsAfterWriteExceptSameIndex()
static bool haveNoReadsAfterWriteExceptSameIndex (ParallelOp firstPloop, ParallelOp secondPloop, const BlockAndValueMapping & firstToSecondPloopIndices) static
Checks if the parallel loops have mixed access to the same buffers.
Returns true if the first parallel loop writes to the same indices that the second loop reads.
Definition at line 59 of file ParallelLoopFusion.cpp.
References mlir::WalkResult::advance(), and mlir::WalkResult::interrupt().
Referenced by verifyDependencies().
isFusionLegal()
static bool isFusionLegal (ParallelOp firstPloop, ParallelOp secondPloop, const BlockAndValueMapping & firstToSecondPloopIndices) static
Definition at line 114 of file ParallelLoopFusion.cpp.
References equalIterationSpaces(), hasNestedParallelOp(), mlir::succeeded(), and verifyDependencies().
Referenced by fuseIfLegal().
verifyDependencies()
static LogicalResult verifyDependencies (ParallelOp firstPloop, ParallelOp secondPloop, const BlockAndValueMapping & firstToSecondPloopIndices) static
Analyzes dependencies in the most primitive way by checking simple read and write patterns.
Definition at line 100 of file ParallelLoopFusion.cpp.
References mlir::failure(), haveNoReadsAfterWriteExceptSameIndex(), mlir::BlockAndValueMapping::map(), and mlir::success().
Referenced by isFusionLegal().