MLIR: lib/Transforms/SCCP.cpp File Reference
SCCP.cpp File Reference
#include "mlir/Transforms/Passes.h"
#include "mlir/Analysis/DataFlow/ConstantPropagationAnalysis.h"
#include "mlir/Analysis/DataFlow/DeadCodeAnalysis.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Dialect.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_SCCP
Functions
static LogicalResult replaceWithConstant (DataFlowSolver &solver, OpBuilder &builder, OperationFolder &folder, Value value)
Replace the given value with a constant if the corresponding lattice represents a constant.
static void rewrite (DataFlowSolver &solver, MLIRContext *context, MutableArrayRef< Region > initialRegions)
Rewrite the given regions using the computing analysis.
Macro Definition Documentation
GEN_PASS_DEF_SCCP
#define GEN_PASS_DEF_SCCP
Definition at line 28 of file SCCP.cpp.
Function Documentation
replaceWithConstant()
static LogicalResult replaceWithConstant (DataFlowSolver & solver, OpBuilder & builder, OperationFolder & folder, Value value) static
Replace the given value with a constant if the corresponding lattice represents a constant.
Returns success if the value was replaced, failure otherwise.
Definition at line 42 of file SCCP.cpp.
References mlir::failure(), mlir::dataflow::ConstantValue::getConstantDialect(), mlir::dataflow::ConstantValue::getConstantValue(), mlir::OperationFolder::getOrCreateConstant(), mlir::DataFlowSolver::lookupState(), mlir::success(), and value.
Referenced by rewrite().
rewrite()
static void rewrite (DataFlowSolver & solver, MLIRContext * context, MutableArrayRef< Region > initialRegions) static
Rewrite the given regions using the computing analysis.
This replaces the uses of all values that have been computed to be constant, and erases as many newly dead operations.
Definition at line 67 of file SCCP.cpp.
References mlir::Block::getArguments(), replaceWithConstant(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), mlir::succeeded(), and mlir::wouldOpBeTriviallyDead().
Referenced by checkAndNestUnderRewriteOp().