MLIR: lib/Dialect/SparseTensor/Transforms/SparseTensorStorageLayout.cpp File Reference
SparseTensorStorageLayout.cpp File Reference
#include "SparseTensorStorageLayout.h"
#include "CodegenUtils.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Transforms/DialectConversion.h"
Macros
#define RETURN_ON_FALSE(idx, kind, dim, dlt)
Functions
static Value createIndexCast (OpBuilder &builder, Location loc, Value value, Type to)
static IntegerAttr fromOptionalInt (MLIRContext *ctx, std::optional< unsigned > dim)
static std::optional< LogicalResult > convertSparseTensorType (RankedTensorType rtp, SmallVectorImpl< Type > &fields)
Variables
constexpr uint64_t kDataFieldStartingIdx = 0
Macro Definition Documentation
RETURN_ON_FALSE
#define RETURN_ON_FALSE (idx, kind, dim, dlt)
Value:
  if (!(callback(idx, kind, dim, dlt)))                                        \
    return;
Function Documentation
convertSparseTensorType()
static std::optional<LogicalResult> convertSparseTensorType (RankedTensorType rtp, SmallVectorImpl< Type > & fields) static
Definition at line 33 of file SparseTensorStorageLayout.cpp.
References mlir::sparse_tensor::foreachFieldAndTypeInSparseTensor(), mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::success().
Referenced by mlir::SparseTensorTypeToBufferConverter::SparseTensorTypeToBufferConverter().
createIndexCast()
static Value createIndexCast (OpBuilder & builder, Location loc, Value value, Type to) static
Definition at line 18 of file SparseTensorStorageLayout.cpp.
References mlir::OpBuilder::create(), and value.
Referenced by mlir::sparse_tensor::SparseTensorSpecifier::getSpecifierField(), and mlir::sparse_tensor::SparseTensorSpecifier::setSpecifierField().
fromOptionalInt()
static IntegerAttr fromOptionalInt (MLIRContext * ctx, std::optional< unsigned > dim) static
Definition at line 25 of file SparseTensorStorageLayout.cpp.
Referenced by mlir::sparse_tensor::SparseTensorSpecifier::getSpecifierField(), and mlir::sparse_tensor::SparseTensorSpecifier::setSpecifierField().
Variable Documentation
kDataFieldStartingIdx
constexpr uint64_t kDataFieldStartingIdx = 0 constexpr
Definition at line 117 of file SparseTensorStorageLayout.cpp.
Referenced by mlir::sparse_tensor::foreachFieldInSparseTensor(), and mlir::sparse_tensor::getNumDataFieldsFromEncoding().