MLIR: lib/Dialect/SparseTensor/Transforms/Sparsification.cpp File Reference
Sparsification.cpp File Reference
#include "CodegenEnv.h"
#include "CodegenUtils.h"
#include "LoopEmitter.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/Transforms/Transforms.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Dialect/SparseTensor/Utils/Merger.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/TensorEncoding.h"
#include "llvm/ADT/SmallBitVector.h"
Functions
static bool isInvariantAffine (AffineExpr a, ArrayRef< unsigned > loopStack, unsigned ldx, bool &atLevel)
Determines if affine expression is invariant.
static bool isInvariantAffine (CodegenEnv &env, AffineExpr a, unsigned ldx, bool &atLevel)
Determines if affine expression is invariant.
static AffineMap permute (CodegenEnv &env, AffineMap m)
Helper method to construct a permuted dimension ordering that adheres to the given topological sort.
static bool findAffine (Merger &merger, unsigned tensor, unsigned dim, AffineExpr a, DimLevelType dlt, unsigned &filterLdx, bool setLvlFormat=true)
Helper method to inspect affine expressions.
static unsigned getNumCompoundAffineOnSparseDims (AffineMap affineMap, Value tensor)
Get the total number of compound affine expressions in affineMap that are attached to the given tensor.
static unsigned getNumCompoundAffineOnSparseDims (linalg::GenericOp op)
Get the total number of compound affine expressions attached on a sparse level in the given GenericOp.
static bool findSparseAnnotations (CodegenEnv &env)
Helper method to inspect sparse encodings in the tensor types.
static bool topSortOptimal (CodegenEnv &env, unsigned n, ArrayRef< utils::IteratorType > iteratorTypes, std::vector< unsigned > &inDegree, std::vector< std::vector< bool >> &adjM)
A helper to compute a topological sort.
static void addAffineOrderings (std::vector< std::vector< bool >> &adjM, std::vector< unsigned > &inDegree, AffineExpr a, AffineExpr b, Optional< unsigned > fidx, Optional< unsigned > tidx)
Helper method to add all constraints from the indices in one affine expression before all indices in the other affine expression.
static void tryLoosenAffineDenseConstraints (linalg::GenericOp op, Optional< unsigned > &fldx, AffineExpr &fa, Optional< unsigned > &tldx, AffineExpr &ta)
static bool computeIterationGraph (CodegenEnv &env, unsigned mask, OpOperand *skip=nullptr)
Computes a topologically sorted iteration graph for the linalg operation.
static bool isMaterializing (Value val)
Returns true if tensor materializes uninitialized into the computation.
static bool isAdmissibleTensorExp (CodegenEnv &env, unsigned exp, OpOperand **sparseOut, unsigned *outerParNest)
Returns true when the tensor expression is admissible for codegen.
static void genBuffers (CodegenEnv &env, OpBuilder &builder)
Local bufferization of all dense and sparse data structures.
static Value genIndex (CodegenEnv &env, OpOperand *t)
Generates index for load/store on sparse tensor.
static Value genSubscript (CodegenEnv &env, OpBuilder &builder, OpOperand *t, SmallVectorImpl< Value > &args)
Generates subscript for load/store on a dense or sparse tensor.
static Value genInsertionLoad (CodegenEnv &env, OpBuilder &builder, OpOperand *t)
Generates insertion code to implement dynamic tensor load.
static Value genInsertionLoadReduce (CodegenEnv &env, OpBuilder &builder, OpOperand *t)
Generates insertion code to implement dynamic tensor load for reduction.
static void genInsertionStore (CodegenEnv &env, OpBuilder &builder, OpOperand *t, Value rhs)
Generates insertion code to implement dynamic tensor store.
static Value genTensorLoad (CodegenEnv &env, OpBuilder &builder, unsigned exp)
Generates a load on a dense or sparse tensor.
static void genTensorStore (CodegenEnv &env, OpBuilder &builder, unsigned exp, Value rhs)
Generates a store on a dense or sparse tensor.
static Value genInvariantValue (CodegenEnv &env, unsigned exp)
Generates an invariant value.
static Value genIndexValue (CodegenEnv &env, unsigned idx)
Generates an index value.
static Value relinkBranch (CodegenEnv &env, RewriterBase &rewriter, Block *block, Value e, unsigned ldx)
Semi-ring branches are simply inlined by the sparse compiler.
static Value genExp (CodegenEnv &env, RewriterBase &rewriter, unsigned exp, unsigned ldx)
Recursively generates tensor expression.
static void genInvariants (CodegenEnv &env, OpBuilder &builder, unsigned exp, unsigned ldx, bool atStart)
Hoists loop invariant tensor loads for which indices have been exhausted.
static void genExpand (CodegenEnv &env, OpBuilder &builder, unsigned at, bool atStart)
Generates an expanded access pattern in innermost dimension.
static bool isParallelFor (CodegenEnv &env, bool isOuter, bool isSparse)
Returns parallelization strategy.
static Operation * genFor (CodegenEnv &env, OpBuilder &builder, bool isOuter, bool isInner, unsigned idx, ArrayRef< size_t > tids, ArrayRef< size_t > dims)
Generates a for-loop on a single index.
static Operation * genWhile (CodegenEnv &env, OpBuilder &builder, unsigned idx, bool needsUniv, ArrayRef< size_t > tids, ArrayRef< size_t > dims)
Emit a while-loop for co-iteration over multiple indices.
static Operation * genLoop (CodegenEnv &env, OpBuilder &builder, unsigned at, bool needsUniv, ArrayRef< size_t > tids, ArrayRef< size_t > dims, bool isFor)
Generates a for-loop or a while-loop, depending on whether it implements singleton iteration or co-iteration over the given conjunction.
static void finalizeWhileOp (CodegenEnv &env, OpBuilder &builder, unsigned idx, bool needsUniv, BitVector &induction, scf::WhileOp whileOp)
Generates the induction structure for a while-loop.
static scf::IfOp genIf (CodegenEnv &env, OpBuilder &builder, unsigned idx, BitVector &conditions)
Generates a single if-statement within a while-loop.
static void endIf (CodegenEnv &env, OpBuilder &builder, scf::IfOp ifOp, Operation *loop, Value redInput, Value cntInput, Value insInput)
Generates end of true branch of if-statement within a while-loop.
static bool startLoopSeq (CodegenEnv &env, OpBuilder &builder, unsigned exp, unsigned at, unsigned idx, unsigned ldx, unsigned lts)
Starts a loop sequence at given level.
static void genConstantDenseAddressFromLevel (CodegenEnv &env, OpBuilder &builder, unsigned tid, unsigned lvl)
static void genInitConstantDenseAddress (CodegenEnv &env, RewriterBase &rewriter)
static bool translateBitsToTidDimPairs (CodegenEnv &env, unsigned li, unsigned idx, SmallVectorImpl< size_t > &tids, SmallVectorImpl< size_t > &dims, SmallVectorImpl< size_t > &affineTids, SmallVectorImpl< size_t > &affineDims, SmallVectorImpl< AffineExpr > &exps)
Return true if the lattices bit can be iterated by a for loop.
static Operation * startLoop (CodegenEnv &env, OpBuilder &builder, unsigned at, unsigned li, bool needsUniv)
Starts a single loop in current sequence.
static bool endLoop (CodegenEnv &env, RewriterBase &rewriter, Operation *loop, unsigned idx, unsigned li, bool needsUniv)
Ends a single loop in current sequence. Returns new values for needsUniv.
static void endLoopSeq (CodegenEnv &env, OpBuilder &builder, unsigned exp, unsigned at, unsigned idx, unsigned ldx)
Ends a loop sequence at given level.
static void genStmt (CodegenEnv &env, RewriterBase &rewriter, unsigned exp, unsigned at)
Recursively generates code while computing iteration lattices in order to manage the complexity of implementing co-iteration over unions and intersections of sparse iterations spaces.
static void genResult (CodegenEnv &env, RewriterBase &rewriter)
Converts the result computed by the sparse kernel into the required form.
Function Documentation
addAffineOrderings()
static void addAffineOrderings (std::vector< std::vector< bool >> & adjM, std::vector< unsigned > & inDegree, AffineExpr a, AffineExpr b, Optional< unsigned > fidx, Optional< unsigned > tidx) static
Helper method to add all constraints from the indices in one affine expression before all indices in the other affine expression.
For example i0+i1 < i2+i3+1 yields i0<i2, i0<i3, i1<i2, and i1<i3. The affine expression a is empty iff fidx have a value, leading to b = (i0 + i1) < fidx => i0 < fidx, i1 < fidx. The affine expression b is empty iff tidx have a value, leading to tidx < a = (i0 + i1) => tidx < i0, tidx < i1.
Definition at line 346 of file Sparsification.cpp.
References mlir::Add, mlir::DimId, and mlir::Mul.
Referenced by computeIterationGraph().
computeIterationGraph()
static bool computeIterationGraph (CodegenEnv & env, unsigned mask, OpOperand * skip = nullptr) static
Computes a topologically sorted iteration graph for the linalg operation.
Ensures all tensors are visited in natural index order. This is essential for sparse storage formats since these only support access along fixed dimensions. Even for dense storage formats, however, the natural index order yields innermost unit-stride access with better spatial locality.
Definition at line 428 of file Sparsification.cpp.
References addAffineOrderings(), mlir::sparse_tensor::CodegenEnv::dlt(), mlir::sparse_tensor::getDimLevelType(), mlir::sparse_tensor::Merger::getLoopIdx(), getNumCompoundAffineOnSparseDims(), mlir::sparse_tensor::Merger::getNumLoops(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::AffineExpr::isa(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::Merger::isFilterLoop(), mlir::sparse_tensor::isSingletonDLT(), mlir::sparse_tensor::isUndefDLT(), mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::CodegenEnv::op(), mlir::sparse_tensor::toOrigDim(), mlir::sparse_tensor::CodegenEnv::topSortClear(), topSortOptimal(), and tryLoosenAffineDenseConstraints().
endIf()
static void endIf (CodegenEnv & env, OpBuilder & builder, scf::IfOp ifOp, Operation * loop, Value redInput, Value cntInput, Value insInput) static
Generates end of true branch of if-statement within a while-loop.
Definition at line 1162 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::sparse_tensor::CodegenEnv::getExpandCount(), mlir::sparse_tensor::CodegenEnv::getInsertionChain(), mlir::sparse_tensor::CodegenEnv::getReduc(), mlir::sparse_tensor::CodegenEnv::isExpand(), mlir::sparse_tensor::CodegenEnv::isReduc(), mlir::sparse_tensor::CodegenEnv::op(), mlir::OpBuilder::setInsertionPointToStart(), mlir::sparse_tensor::CodegenEnv::updateExpandCount(), mlir::sparse_tensor::CodegenEnv::updateInsertionChain(), and mlir::sparse_tensor::CodegenEnv::updateReduc().
Referenced by genStmt().
endLoop()
static bool endLoop (CodegenEnv & env, RewriterBase & rewriter, Operation * loop, unsigned idx, unsigned li, bool needsUniv) static
Ends a single loop in current sequence. Returns new values for needsUniv.
Definition at line 1388 of file Sparsification.cpp.
References mlir::sparse_tensor::LatPoint::bits, mlir::sparse_tensor::CodegenEnv::emitter(), finalizeWhileOp(), mlir::sparse_tensor::CodegenEnv::genLoopBoundary(), mlir::sparse_tensor::CodegenEnv::lat(), and mlir::sparse_tensor::CodegenEnv::op().
Referenced by genStmt().
endLoopSeq()
static void endLoopSeq (CodegenEnv & env, OpBuilder & builder, unsigned exp, unsigned at, unsigned idx, unsigned ldx) static
Ends a loop sequence at given level.
Definition at line 1406 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::emitter(), mlir::sparse_tensor::LoopEmitter::exitCurrentLoopSeq(), genExpand(), genInvariants(), and mlir::sparse_tensor::CodegenEnv::getLoopIdxValue().
Referenced by genStmt().
finalizeWhileOp()
static void finalizeWhileOp (CodegenEnv & env, OpBuilder & builder, unsigned idx, bool needsUniv, BitVector & induction, scf::WhileOp whileOp) static
Generates the induction structure for a while-loop.
Definition at line 1095 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::sparse_tensor::CodegenEnv::getExpandCount(), mlir::OpBuilder::getInsertionBlock(), mlir::sparse_tensor::CodegenEnv::getInsertionChain(), mlir::Block::getParentOp(), mlir::sparse_tensor::CodegenEnv::getReduc(), mlir::sparse_tensor::CodegenEnv::isExpand(), mlir::sparse_tensor::CodegenEnv::isReduc(), mlir::sparse_tensor::CodegenEnv::op(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::sparse_tensor::CodegenEnv::updateExpandCount(), mlir::sparse_tensor::CodegenEnv::updateInsertionChain(), and mlir::sparse_tensor::CodegenEnv::updateReduc().
Referenced by endLoop().
findAffine()
static bool findAffine (Merger & merger, unsigned tensor, unsigned dim, AffineExpr a, DimLevelType dlt, unsigned & filterLdx, bool setLvlFormat = true) static
Helper method to inspect affine expressions.
Rejects cases where the same index is used more than once. Also rejects compound affine expressions in sparse dimensions. filterIdx stores the current filter loop idx should be used for the next compound affine sparse level, and it will be incremented by one when used.
Definition at line 176 of file Sparsification.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::Constant, mlir::DimId, mlir::AffineExpr::dyn_cast(), mlir::sparse_tensor::Merger::getDimLevelType(), mlir::AffineExpr::getKind(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::isUndefDLT(), mlir::Mul, and mlir::sparse_tensor::Merger::setDimAndDimLevelType().
Referenced by findSparseAnnotations().
findSparseAnnotations()
static bool findSparseAnnotations (CodegenEnv & env) static
Helper method to inspect sparse encodings in the tensor types.
Fills the per-dimension sparsity information for all tensors. Returns true if the sparse annotations and affine subscript expressions of all tensors are admissible. Returns false if no annotations are found or inadmissible constructs occur.
Definition at line 257 of file Sparsification.cpp.
References findAffine(), mlir::sparse_tensor::getDimLevelType(), mlir::sparse_tensor::Merger::getFilterLoopStartingIdx(), mlir::sparse_tensor::Merger::getNumLoops(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::CodegenEnv::op(), and mlir::sparse_tensor::toOrigDim().
genBuffers()
static void genBuffers (CodegenEnv & env, OpBuilder & builder) static
Local bufferization of all dense and sparse data structures.
Generates buffer for the output tensor. Note that all sparse kernels assume that when all elements are written to (viz. x(i) = y(i) * z(i)), the output buffer is already initialized to all zeroes and only nonzeroes values are computed and written out. For updates (viz. x(i) += y(i) * z(i)), only nonzeroes values are used for the updates and no assumption on the original contents of the output buffer is necessary.
Definition at line 609 of file Sparsification.cpp.
References mlir::sparse_tensor::constantZero(), mlir::OpBuilder::create(), mlir::sparse_tensor::CodegenEnv::emitter(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::getElementTypeOrSelf(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), mlir::sparse_tensor::LoopEmitter::initializeLoopEmit(), and mlir::sparse_tensor::CodegenEnv::op().
genConstantDenseAddressFromLevel()
static void genConstantDenseAddressFromLevel (CodegenEnv & env, OpBuilder & builder, unsigned tid, unsigned lvl) static
Definition at line 1231 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::emitter(), mlir::sparse_tensor::LoopEmitter::genDenseAffineAddressAtCurLevel(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::sparse_tensor::getDimLevelType(), mlir::OpOperand::getOperandNumber(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), mlir::AffineExpr::isa(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::CodegenEnv::op(), and mlir::sparse_tensor::toOrigDim().
Referenced by genInitConstantDenseAddress(), and startLoop().
genExp()
static Value genExp (CodegenEnv & env, RewriterBase & rewriter, unsigned exp, unsigned ldx) static
Recursively generates tensor expression.
Definition at line 866 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::buildExp(), mlir::sparse_tensor::TensorExp::children, mlir::sparse_tensor::Children::e0, mlir::sparse_tensor::Children::e1, mlir::sparse_tensor::CodegenEnv::endCustomReduc(), mlir::sparse_tensor::CodegenEnv::exp(), genIndexValue(), genInvariantValue(), genTensorLoad(), mlir::Value::getParentBlock(), mlir::sparse_tensor::TensorExp::index, mlir::sparse_tensor::kBinary, mlir::sparse_tensor::kBinaryBranch, mlir::sparse_tensor::TensorExp::kind, mlir::sparse_tensor::kIndex, mlir::sparse_tensor::kInvariant, mlir::sparse_tensor::kReduce, mlir::sparse_tensor::kSelect, mlir::sparse_tensor::kTensor, mlir::sparse_tensor::kUnary, mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::CodegenEnv::op(), relinkBranch(), mlir::sparse_tensor::CodegenEnv::startCustomReduc(), and mlir::sparse_tensor::TensorExp::val.
Referenced by genStmt().
genExpand()
static void genExpand (CodegenEnv & env, OpBuilder & builder, unsigned at, bool atStart) static
Generates an expanded access pattern in innermost dimension.
Definition at line 963 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::atExpandLevel(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::sparse_tensor::CodegenEnv::emitter(), mlir::sparse_tensor::CodegenEnv::endExpand(), mlir::IROperand< DerivedT, IRValueT >::get(), getElementType(), mlir::sparse_tensor::CodegenEnv::getExpandAdded(), mlir::sparse_tensor::CodegenEnv::getExpandCount(), mlir::sparse_tensor::CodegenEnv::getExpandFilled(), mlir::sparse_tensor::CodegenEnv::getExpandValues(), mlir::Builder::getI1Type(), mlir::Builder::getIndexType(), mlir::sparse_tensor::CodegenEnv::getInsertionChain(), mlir::sparse_tensor::LoopEmitter::getLoopIV(), mlir::Value::getType(), mlir::sparse_tensor::CodegenEnv::isReduc(), mlir::sparse_tensor::CodegenEnv::op(), mlir::sparse_tensor::CodegenEnv::startExpand(), and mlir::sparse_tensor::CodegenEnv::updateInsertionChain().
Referenced by endLoopSeq(), and startLoopSeq().
genFor()
static Operation* genFor (CodegenEnv & env, OpBuilder & builder, bool isOuter, bool isInner, unsigned idx, ArrayRef< size_t > tids, ArrayRef< size_t > dims) static
Generates a for-loop on a single index.
Definition at line 1031 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::dlt(), mlir::sparse_tensor::CodegenEnv::emitter(), mlir::sparse_tensor::LoopEmitter::enterLoopOverTensorAtDim(), mlir::sparse_tensor::CodegenEnv::genLoopBoundary(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::Merger::isFilterLoop(), isParallelFor(), mlir::sparse_tensor::isSingletonDLT(), mlir::sparse_tensor::CodegenEnv::merger(), and mlir::sparse_tensor::CodegenEnv::op().
Referenced by genLoop().
genIf()
static scf::IfOp genIf (CodegenEnv & env, OpBuilder & builder, unsigned idx, BitVector & conditions) static
Generates a single if-statement within a while-loop.
Definition at line 1126 of file Sparsification.cpp.
References mlir::sparse_tensor::constantI1(), mlir::OpBuilder::create(), mlir::sparse_tensor::CodegenEnv::dlt(), mlir::sparse_tensor::CodegenEnv::emitter(), mlir::sparse_tensor::LoopEmitter::getCoord(), mlir::sparse_tensor::Merger::getDimLevelType(), mlir::sparse_tensor::Merger::getDimNum(), mlir::Builder::getIndexType(), mlir::sparse_tensor::CodegenEnv::getInsertionChain(), mlir::sparse_tensor::CodegenEnv::getLoopIdxValue(), mlir::sparse_tensor::CodegenEnv::getReduc(), mlir::Value::getType(), mlir::sparse_tensor::Merger::index(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::CodegenEnv::isExpand(), mlir::sparse_tensor::CodegenEnv::isReduc(), mlir::sparse_tensor::isSingletonDLT(), mlir::sparse_tensor::isUndefDLT(), mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::CodegenEnv::op(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::sparse_tensor::Merger::tensor().
Referenced by genStmt().
genIndex()
static Value genIndex (CodegenEnv & env, OpOperand * t) static
Generates index for load/store on sparse tensor.
Definition at line 651 of file Sparsification.cpp.
References mlir::AffineExpr::cast(), mlir::DimId, mlir::IROperand< DerivedT, IRValueT >::get(), mlir::AffineExpr::getKind(), mlir::sparse_tensor::CodegenEnv::getLoopIdxValue(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), mlir::sparse_tensor::CodegenEnv::op(), and mlir::sparse_tensor::toOrigDim().
Referenced by genInsertionLoad(), genInsertionLoadReduce(), and genInsertionStore().
genIndexValue()
static Value genIndexValue (CodegenEnv & env, unsigned idx) inline static
Generates an index value.
Definition at line 842 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::getLoopIdxValue().
Referenced by genExp(), and relinkBranch().
genInitConstantDenseAddress()
static void genInitConstantDenseAddress (CodegenEnv & env, RewriterBase & rewriter) static
Definition at line 1253 of file Sparsification.cpp.
References genConstantDenseAddressFromLevel(), and mlir::sparse_tensor::CodegenEnv::op().
genInsertionLoad()
static Value genInsertionLoad (CodegenEnv & env, OpBuilder & builder, OpOperand * t) static
Generates insertion code to implement dynamic tensor load.
Definition at line 682 of file Sparsification.cpp.
References mlir::sparse_tensor::constantZero(), mlir::OpBuilder::create(), genIndex(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::getElementTypeOrSelf(), mlir::sparse_tensor::CodegenEnv::getExpandValues(), mlir::Value::getType(), mlir::sparse_tensor::CodegenEnv::isExpand(), and mlir::sparse_tensor::CodegenEnv::op().
Referenced by genTensorLoad().
genInsertionLoadReduce()
static Value genInsertionLoadReduce (CodegenEnv & env, OpBuilder & builder, OpOperand * t) static
Generates insertion code to implement dynamic tensor load for reduction.
Definition at line 697 of file Sparsification.cpp.
References mlir::OpBuilder::create(), genIndex(), mlir::sparse_tensor::CodegenEnv::getCustomRedId(), mlir::sparse_tensor::CodegenEnv::getExpandFilled(), mlir::sparse_tensor::CodegenEnv::getExpandValues(), mlir::sparse_tensor::CodegenEnv::isExpand(), and mlir::sparse_tensor::CodegenEnv::op().
Referenced by genTensorLoad().
genInsertionStore()
static void genInsertionStore (CodegenEnv & env, OpBuilder & builder, OpOperand * t, Value rhs) static
Generates insertion code to implement dynamic tensor store.
Definition at line 715 of file Sparsification.cpp.
References mlir::sparse_tensor::constantI1(), mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), mlir::sparse_tensor::CodegenEnv::emitter(), genIndex(), mlir::sparse_tensor::CodegenEnv::getExpandAdded(), mlir::sparse_tensor::CodegenEnv::getExpandCount(), mlir::sparse_tensor::CodegenEnv::getExpandFilled(), mlir::sparse_tensor::CodegenEnv::getExpandValues(), mlir::Builder::getIndexType(), mlir::sparse_tensor::CodegenEnv::getInsertionChain(), mlir::sparse_tensor::LoopEmitter::getLoopIV(), mlir::sparse_tensor::CodegenEnv::isExpand(), mlir::sparse_tensor::CodegenEnv::op(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), mlir::sparse_tensor::CodegenEnv::updateExpandCount(), and mlir::sparse_tensor::CodegenEnv::updateInsertionChain().
Referenced by genTensorStore().
genInvariants()
static void genInvariants (CodegenEnv & env, OpBuilder & builder, unsigned exp, unsigned ldx, bool atStart) static
Hoists loop invariant tensor loads for which indices have been exhausted.
Definition at line 905 of file Sparsification.cpp.
References mlir::sparse_tensor::TensorExp::children, mlir::sparse_tensor::Children::e0, mlir::sparse_tensor::Children::e1, mlir::sparse_tensor::CodegenEnv::endCustomReduc(), mlir::sparse_tensor::CodegenEnv::endReduc(), mlir::sparse_tensor::CodegenEnv::exp(), genTensorLoad(), genTensorStore(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::sparse_tensor::CodegenEnv::getCustomRedId(), mlir::sparse_tensor::Merger::getLoopIdx(), mlir::sparse_tensor::CodegenEnv::getLoopIdxValue(), mlir::OpOperand::getOperandNumber(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), mlir::sparse_tensor::CodegenEnv::isCustomReduc(), mlir::sparse_tensor::Merger::isFilterLoop(), isInvariantAffine(), mlir::sparse_tensor::TensorExp::kind, mlir::sparse_tensor::kIndex, mlir::sparse_tensor::kInvariant, mlir::sparse_tensor::kReduce, mlir::sparse_tensor::kTensor, mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::CodegenEnv::op(), mlir::sparse_tensor::CodegenEnv::startCustomReduc(), mlir::sparse_tensor::CodegenEnv::startReduc(), mlir::sparse_tensor::TensorExp::tensor, mlir::sparse_tensor::toOrigDim(), and mlir::sparse_tensor::TensorExp::val.
Referenced by endLoopSeq(), and startLoopSeq().
genInvariantValue()
static Value genInvariantValue (CodegenEnv & env, unsigned exp) inline static
Generates an invariant value.
Definition at line 837 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::exp(), and mlir::sparse_tensor::TensorExp::val.
Referenced by genExp().
genLoop()
static Operation* genLoop (CodegenEnv & env, OpBuilder & builder, unsigned at, bool needsUniv, ArrayRef< size_t > tids, ArrayRef< size_t > dims, bool isFor) static
Generates a for-loop or a while-loop, depending on whether it implements singleton iteration or co-iteration over the given conjunction.
Definition at line 1081 of file Sparsification.cpp.
References genFor(), genWhile(), mlir::sparse_tensor::CodegenEnv::topSortAt(), and mlir::sparse_tensor::CodegenEnv::topSortSize().
Referenced by startLoop().
genResult()
static void genResult (CodegenEnv & env, RewriterBase & rewriter) static
Converts the result computed by the sparse kernel into the required form.
Definition at line 1477 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::emitter(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::sparse_tensor::CodegenEnv::getInsertionChain(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), mlir::sparse_tensor::LoopEmitter::getValBuffer(), mlir::sparse_tensor::CodegenEnv::op(), and mlir::RewriterBase::replaceOpWithNewOp().
genStmt()
static void genStmt (CodegenEnv & env, RewriterBase & rewriter, unsigned exp, unsigned at) static
Recursively generates code while computing iteration lattices in order to manage the complexity of implementing co-iteration over unions and intersections of sparse iterations spaces.
Definition at line 1419 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::buildLattices(), endIf(), endLoop(), endLoopSeq(), mlir::sparse_tensor::LatPoint::exp, genExp(), genIf(), genTensorStore(), mlir::sparse_tensor::CodegenEnv::getExpandCount(), mlir::sparse_tensor::CodegenEnv::getInsertionChain(), mlir::sparse_tensor::CodegenEnv::getReduc(), mlir::sparse_tensor::CodegenEnv::lat(), mlir::sparse_tensor::Merger::latGT(), mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::Merger::optimizeSet(), mlir::sparse_tensor::CodegenEnv::set(), mlir::sparse_tensor::LatPoint::simple, startLoop(), startLoopSeq(), mlir::sparse_tensor::CodegenEnv::topSortAt(), and mlir::sparse_tensor::CodegenEnv::topSortSize().
genSubscript()
static Value genSubscript (CodegenEnv & env, OpBuilder & builder, OpOperand * t, SmallVectorImpl< Value > & args) static
Generates subscript for load/store on a dense or sparse tensor.
Definition at line 661 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::emitter(), mlir::sparse_tensor::LoopEmitter::genAffine(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::sparse_tensor::LoopEmitter::getPidxs(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), mlir::sparse_tensor::LoopEmitter::getValBuffer(), and mlir::sparse_tensor::CodegenEnv::op().
Referenced by genTensorLoad(), and genTensorStore().
genTensorLoad()
static Value genTensorLoad (CodegenEnv & env, OpBuilder & builder, unsigned exp) static
Generates a load on a dense or sparse tensor.
Definition at line 768 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::sparse_tensor::CodegenEnv::exp(), genInsertionLoad(), genInsertionLoadReduce(), genSubscript(), mlir::sparse_tensor::CodegenEnv::isCustomReduc(), mlir::sparse_tensor::CodegenEnv::isSparseOutput(), mlir::sparse_tensor::CodegenEnv::op(), mlir::sparse_tensor::TensorExp::tensor, and mlir::sparse_tensor::TensorExp::val.
Referenced by genExp(), and genInvariants().
genTensorStore()
static void genTensorStore (CodegenEnv & env, OpBuilder & builder, unsigned exp, Value rhs) static
Generates a store on a dense or sparse tensor.
Definition at line 789 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::sparse_tensor::CodegenEnv::exp(), genInsertionStore(), genSubscript(), mlir::sparse_tensor::CodegenEnv::getInsertionChain(), mlir::Value::getType(), mlir::sparse_tensor::CodegenEnv::isReduc(), mlir::sparse_tensor::CodegenEnv::isSparseOutput(), mlir::sparse_tensor::kBinary, mlir::sparse_tensor::TensorExp::kind, mlir::sparse_tensor::kSelect, mlir::sparse_tensor::kUnary, mlir::sparse_tensor::CodegenEnv::op(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), mlir::sparse_tensor::CodegenEnv::updateInsertionChain(), mlir::sparse_tensor::CodegenEnv::updateReduc(), and mlir::sparse_tensor::TensorExp::val.
Referenced by genInvariants(), and genStmt().
genWhile()
static Operation* genWhile (CodegenEnv & env, OpBuilder & builder, unsigned idx, bool needsUniv, ArrayRef< size_t > tids, ArrayRef< size_t > dims) static
Emit a while-loop for co-iteration over multiple indices.
Definition at line 1066 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::emitter(), mlir::sparse_tensor::CodegenEnv::genLoopBoundary(), and mlir::sparse_tensor::CodegenEnv::op().
Referenced by genLoop().
getNumCompoundAffineOnSparseDims() [1/2]
static unsigned getNumCompoundAffineOnSparseDims (AffineMap affineMap, Value tensor) static
Get the total number of compound affine expressions in affineMap that are attached to the given tensor.
For the following inputs:
affineMap = (d0, d1, d2) => (d0 + d1, d2) tensor = ["compressed", "compressed"]
Returns 1 (because the first level is compressed and its corresponding affineMap is d0 + d1)
Definition at line 224 of file Sparsification.cpp.
References mlir::sparse_tensor::getDimLevelType(), mlir::AffineMap::getResults(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), mlir::sparse_tensor::isDenseDLT(), and mlir::sparse_tensor::toOrigDim().
Referenced by computeIterationGraph(), getNumCompoundAffineOnSparseDims(), and isAdmissibleTensorExp().
getNumCompoundAffineOnSparseDims() [2/2]
static unsigned getNumCompoundAffineOnSparseDims (linalg::GenericOp op) static
Get the total number of compound affine expressions attached on a sparse level in the given GenericOp.
Definition at line 244 of file Sparsification.cpp.
References getNumCompoundAffineOnSparseDims().
isAdmissibleTensorExp()
static bool isAdmissibleTensorExp (CodegenEnv & env, unsigned exp, OpOperand ** sparseOut, unsigned * outerParNest) static
Returns true when the tensor expression is admissible for codegen.
Since all sparse input tensors are admissible, we just need to check whether the out tensor in the tensor expression codegen is admissible. Sets sparseOut to the tensor and outerParNest to the outer injective nesting depth when a "truly dynamic" sparse tensor output occurs.
Definition at line 529 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::dlt(), mlir::IROperand< DerivedT, IRValueT >::get(), getNumCompoundAffineOnSparseDims(), mlir::sparse_tensor::Merger::getNumLoops(), mlir::OpOperand::getOperandNumber(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), mlir::sparse_tensor::Merger::hasNegateOnOut(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::Merger::isFilterLoop(), isMaterializing(), mlir::linalg::isReductionIterator(), mlir::sparse_tensor::Merger::isSingleCondition(), mlir::sparse_tensor::isSingletonDLT(), mlir::sparse_tensor::isUndefDLT(), mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::CodegenEnv::op(), and mlir::sparse_tensor::CodegenEnv::topSortAt().
isInvariantAffine() [1/2]
static bool isInvariantAffine (AffineExpr a, ArrayRef< unsigned > loopStack, unsigned ldx, bool & atLevel) static
Determines if affine expression is invariant.
Definition at line 91 of file Sparsification.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::DimId, mlir::AffineExpr::getKind(), mlir::AffineExpr::isa(), and mlir::Mul.
Referenced by genInvariants(), isInvariantAffine(), permute(), and translateBitsToTidDimPairs().
isInvariantAffine() [2/2]
static bool isInvariantAffine (CodegenEnv & env, AffineExpr a, unsigned ldx, bool & atLevel) static
Determines if affine expression is invariant.
Definition at line 123 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::getLoopCurStack(), and isInvariantAffine().
isMaterializing()
static bool isMaterializing (Value val) static
Returns true if tensor materializes uninitialized into the computation.
Definition at line 519 of file Sparsification.cpp.
References mlir::Value::getDefiningOp().
Referenced by isAdmissibleTensorExp().
isParallelFor()
static bool isParallelFor (CodegenEnv & env, bool isOuter, bool isSparse) static
Returns parallelization strategy.
Any implicit loop in the Linalg operation that is marked "parallel" is a candidate. Whether it is actually converted to a parallel operation depends on the requested strategy.
Definition at line 1007 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::hasSparseOutput(), mlir::sparse_tensor::CodegenEnv::isExpand(), mlir::kAnyStorageAnyLoop, mlir::kAnyStorageOuterLoop, mlir::kDenseAnyLoop, mlir::kDenseOuterLoop, mlir::kNone, mlir::sparse_tensor::CodegenEnv::options(), and mlir::SparsificationOptions::parallelizationStrategy.
Referenced by genFor().
permute()
static AffineMap permute (CodegenEnv & env, AffineMap m) static
Helper method to construct a permuted dimension ordering that adheres to the given topological sort.
Definition at line 130 of file Sparsification.cpp.
References mlir::AffineMap::getNumDims(), mlir::sparse_tensor::Merger::getNumFilterLoops(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getPermutationMap(), mlir::AffineMap::getResult(), mlir::sparse_tensor::CodegenEnv::getTopSortSlice(), mlir::AffineExpr::isa(), isInvariantAffine(), mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::CodegenEnv::op(), mlir::sparse_tensor::CodegenEnv::topSortAt(), and mlir::sparse_tensor::CodegenEnv::topSortSize().
Referenced by mlir::sparse_tensor::detail::PermutationRef::permute().
relinkBranch()
static Value relinkBranch (CodegenEnv & env, RewriterBase & rewriter, Block * block, Value e, unsigned ldx) static
Semi-ring branches are simply inlined by the sparse compiler.
Prior analysis has verified that all computations are "local" to the inlined branch or otherwise invariantly defined outside the loop nest, with the exception of index computations, which need to be relinked to actual inlined cloned code.
Definition at line 851 of file Sparsification.cpp.
References genIndexValue(), and mlir::Value::getDefiningOp().
Referenced by genExp().
startLoop()
static Operation* startLoop (CodegenEnv & env, OpBuilder & builder, unsigned at, unsigned li, bool needsUniv) static
Starts a single loop in current sequence.
Definition at line 1355 of file Sparsification.cpp.
References mlir::sparse_tensor::CodegenEnv::emitter(), genConstantDenseAddressFromLevel(), mlir::sparse_tensor::LoopEmitter::genDenseAffineAddressAtCurLevel(), genLoop(), mlir::sparse_tensor::Merger::getOutTensorID(), mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::CodegenEnv::op(), mlir::sparse_tensor::CodegenEnv::topSortAt(), and translateBitsToTidDimPairs().
Referenced by genStmt().
startLoopSeq()
static bool startLoopSeq (CodegenEnv & env, OpBuilder & builder, unsigned exp, unsigned at, unsigned idx, unsigned ldx, unsigned lts) static
Starts a loop sequence at given level.
Returns true if the universal loop index must be maintained at this level.
Definition at line 1189 of file Sparsification.cpp.
References mlir::sparse_tensor::LatPoint::bits, mlir::sparse_tensor::Merger::foreachTidDimPairInBits(), genExpand(), genInvariants(), mlir::sparse_tensor::CodegenEnv::getLoopIdxValue(), mlir::sparse_tensor::CodegenEnv::lat(), mlir::sparse_tensor::CodegenEnv::merger(), and mlir::sparse_tensor::CodegenEnv::set().
Referenced by genStmt().
topSortOptimal()
static bool topSortOptimal (CodegenEnv & env, unsigned n, ArrayRef< utils::IteratorType > iteratorTypes, std::vector< unsigned > & inDegree, std::vector< std::vector< bool >> & adjM) static
A helper to compute a topological sort.
O(n^2) time complexity as we use adj matrix for the graph. The sorted result will put the first Reduction iterator to the latest possible index.
Definition at line 282 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::isFilterLoop(), mlir::linalg::isReductionIterator(), mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::CodegenEnv::topSortPushBack(), and mlir::sparse_tensor::CodegenEnv::topSortSize().
Referenced by computeIterationGraph().
translateBitsToTidDimPairs()
static bool translateBitsToTidDimPairs (CodegenEnv & env, unsigned li, unsigned idx, SmallVectorImpl< size_t > & tids, SmallVectorImpl< size_t > & dims, SmallVectorImpl< size_t > & affineTids, SmallVectorImpl< size_t > & affineDims, SmallVectorImpl< AffineExpr > & exps) static
Return true if the lattices bit can be iterated by a for loop.
Definition at line 1264 of file Sparsification.cpp.
References mlir::sparse_tensor::LatPoint::bits, mlir::sparse_tensor::Merger::foreachTidDimPairInBits(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::sparse_tensor::getDimLevelType(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), mlir::AffineExpr::isa(), mlir::sparse_tensor::isDenseDLT(), isInvariantAffine(), mlir::sparse_tensor::isUndefDLT(), mlir::sparse_tensor::CodegenEnv::lat(), mlir::sparse_tensor::CodegenEnv::merger(), mlir::sparse_tensor::CodegenEnv::op(), mlir::sparse_tensor::LatPoint::simple, and mlir::sparse_tensor::toOrigDim().
Referenced by startLoop().
tryLoosenAffineDenseConstraints()
static void tryLoosenAffineDenseConstraints (linalg::GenericOp op, Optional< unsigned > & fldx, AffineExpr & fa, Optional< unsigned > & tldx, AffineExpr & ta) static
Definition at line 388 of file Sparsification.cpp.
References mlir::AffineExpr::isa().
Referenced by computeIterationGraph().