MLIR: lib/Dialect/SparseTensor/Transforms/SparseStorageSpecifierToLLVM.cpp File Reference
SparseStorageSpecifierToLLVM.cpp File Reference
#include "CodegenUtils.h"
#include "SparseTensorStorageLayout.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
Classes
class SpecifierStructBuilder
class SpecifierGetterSetterOpConverter< Base, SourceOp >
struct StorageSpecifierSetOpConverter
struct StorageSpecifierGetOpConverter
struct StorageSpecifierInitOpConverter
Functions
static SmallVector< Type, 2 > getSpecifierFields (StorageSpecifierType tp)
static Type convertSpecifier (StorageSpecifierType tp)
Variables
constexpr uint64_t kDimSizePosInSpecifier = 0
constexpr uint64_t kMemSizePosInSpecifier = 1
Function Documentation
convertSpecifier()
static Type convertSpecifier (StorageSpecifierType tp) static
Definition at line 32 of file SparseStorageSpecifierToLLVM.cpp.
References mlir::LLVM::LLVMStructType::getLiteral(), and getSpecifierFields().
Referenced by mlir::StorageSpecifierToLLVMTypeConverter::StorageSpecifierToLLVMTypeConverter().
getSpecifierFields()
static SmallVector<Type, 2> getSpecifierFields (StorageSpecifierType tp) static
Definition at line 17 of file SparseStorageSpecifierToLLVM.cpp.
References mlir::sparse_tensor::getNumDataFieldsFromEncoding().
Referenced by convertSpecifier().
Variable Documentation
kDimSizePosInSpecifier
constexpr uint64_t kDimSizePosInSpecifier = 0 constexpr
Definition at line 42 of file SparseStorageSpecifierToLLVM.cpp.
Referenced by SpecifierStructBuilder::dimSize(), and SpecifierStructBuilder::setDimSize().
kMemSizePosInSpecifier
constexpr uint64_t kMemSizePosInSpecifier = 1 constexpr
Definition at line 43 of file SparseStorageSpecifierToLLVM.cpp.
Referenced by SpecifierStructBuilder::getInitValue(), SpecifierStructBuilder::memSize(), and SpecifierStructBuilder::setMemSize().