MLIR: mlir::AffineBuilder Struct Reference
mlir::AffineBuilder Struct Reference
Helper struct to build simple AffineValueExprs with minimal type inference support.
#include "mlir/Dialect/Affine/Utils.h"
Public Member Functions
AffineBuilder (OpBuilder &b, Location loc)
OpFoldResult add (AffineValueExpr lhs, AffineValueExpr rhs)
OpFoldResult sub (AffineValueExpr lhs, AffineValueExpr rhs)
OpFoldResult mul (AffineValueExpr lhs, AffineValueExpr rhs)
OpFoldResult floor (AffineValueExpr lhs, AffineValueExpr rhs)
OpFoldResult ceil (AffineValueExpr lhs, AffineValueExpr rhs)
OpFoldResult min (ArrayRef< OpFoldResult > vals)
OpFoldResult max (ArrayRef< OpFoldResult > vals)
Detailed Description
Helper struct to build simple AffineValueExprs with minimal type inference support.
Definition at line 351 of file Utils.h.
Constructor & Destructor Documentation
AffineBuilder()
mlir::AffineBuilder::AffineBuilder (OpBuilder & b, Location loc) inline
Definition at line 352 of file Utils.h.
Member Function Documentation
add()
OpFoldResult mlir::AffineBuilder::add (AffineValueExpr lhs, AffineValueExpr rhs) inline
Definition at line 353 of file Utils.h.
References mlir::AffineValueExpr::e, and mlir::makeComposedFoldedAffineApply().
ceil()
OpFoldResult mlir::AffineBuilder::ceil (AffineValueExpr lhs, AffineValueExpr rhs) inline
Definition at line 366 of file Utils.h.
References mlir::AffineExpr::ceilDiv(), mlir::AffineValueExpr::e, and mlir::makeComposedFoldedAffineApply().
floor()
OpFoldResult mlir::AffineBuilder::floor (AffineValueExpr lhs, AffineValueExpr rhs) inline
Definition at line 362 of file Utils.h.
References mlir::AffineValueExpr::e, mlir::AffineExpr::floorDiv(), and mlir::makeComposedFoldedAffineApply().
max()
OpFoldResult mlir::AffineBuilder::max (ArrayRef< OpFoldResult > vals) inline
Definition at line 375 of file Utils.h.
References mlir::Builder::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), and mlir::makeComposedFoldedAffineMax().
min()
OpFoldResult mlir::AffineBuilder::min (ArrayRef< OpFoldResult > vals) inline
Definition at line 370 of file Utils.h.
References mlir::Builder::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), and mlir::makeComposedFoldedAffineMin().
mul()
OpFoldResult mlir::AffineBuilder::mul (AffineValueExpr lhs, AffineValueExpr rhs) inline
Definition at line 359 of file Utils.h.
References mlir::AffineValueExpr::e, and mlir::makeComposedFoldedAffineApply().
sub()
OpFoldResult mlir::AffineBuilder::sub (AffineValueExpr lhs, AffineValueExpr rhs) inline
Definition at line 356 of file Utils.h.
References mlir::AffineValueExpr::e, and mlir::makeComposedFoldedAffineApply().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Affine/Utils.h