MLIR: lib/Dialect/Vector/IR/VectorOps.cpp File Reference
VectorOps.cpp File Reference
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/ADT/bit.h"
#include <cassert>
#include <cstdint>
#include <numeric>
#include "mlir/Dialect/Vector/IR/VectorOpsDialect.cpp.inc"
#include "mlir/Dialect/Vector/IR/VectorOpsEnums.cpp.inc"
#include "mlir/Dialect/Vector/IR/VectorOpsAttrDefs.cpp.inc"
#include "mlir/Dialect/Vector/IR/VectorOps.cpp.inc"
Classes
struct mlir::vector::detail::BitmaskEnumStorage
struct CanonicalizeContractAdd< AddOpType >
Return a fused vector::ContractionOp which represents a patterns such as:
Namespaces
mlir
Include the generated interface declarations.
mlir::vector
mlir::vector::detail
Macros
#define GET_ATTRDEF_LIST
#define GET_OP_LIST
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
Enumerations
enum class MaskFormat { AllTrue = 0 , AllFalse = 1 , Unknown = 2 }
Helper enum to classify mask value.
Functions
static MaskFormat getMaskFormat (Value mask)
Helper method to classify a mask value.
static bool isSupportedCombiningKind (CombiningKind combiningKind, Type elementType)
static LogicalResult incSlicePosition (MutableArrayRef< int64_t > position, ArrayRef< int64_t > shape, ArrayRef< int64_t > offsets)
static bool verifyDimMap (VectorType lhsType, VectorType rhsType, const std::vector< std::pair< int64_t, int64_t >> &map)
static LogicalResult verifyOutputShape (ContractionOp op, VectorType lhsType, VectorType rhsType, Type accType, Type resType, const std::vector< std::pair< int64_t, int64_t >> &contractingDimMap, const std::vector< std::pair< int64_t, int64_t >> &batchDimMap)
static int64_t getResultIndex (AffineMap map, AffineExpr targetExpr)
static std::vector< std::pair< int64_t, int64_t > > getDimMap (ArrayRef< AffineMap > indexingMaps, ArrayAttr iteratorTypes, IteratorType targetIteratorType, MLIRContext *context)
template<typename IntType >
static SmallVector< IntType > extractVector (ArrayAttr arrayAttr)
static LogicalResult foldExtractOpFromExtractChain (ExtractOp extractOp)
Fold the result of chains of ExtractOp in place by simply concatenating the positions.
static Value foldExtractFromBroadcast (ExtractOp extractOp)
Fold extractOp with scalar result coming from BroadcastOp or SplatOp.
static Value foldExtractFromShapeCast (ExtractOp extractOp)
static Value foldExtractFromExtractStrided (ExtractOp extractOp)
Fold an ExtractOp from ExtractStridedSliceOp.
static Value foldExtractStridedOpFromInsertChain (ExtractOp op)
Fold extract_op fed from a chain of insertStridedSlice ops.
static void populateFromInt64AttrArray (ArrayAttr arrayAttr, SmallVectorImpl< int64_t > &results)
static llvm::SetVector< int64_t > computeBroadcastedUnitDims (ArrayRef< int64_t > srcShape, ArrayRef< int64_t > dstShape)
Return the dimensions of the result vector that were formerly ones in the source tensor and thus correspond to "dim-1" broadcasting.
static bool isStepIndexArray (ArrayAttr idxArr, uint64_t begin, size_t width)
template<typename OpType >
static LogicalResult isIntegerArrayAttrSmallerThanShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName)
template<typename OpType >
static LogicalResult isIntegerArrayAttrConfinedToRange (OpType op, ArrayAttr arrayAttr, int64_t min, int64_t max, StringRef attrName, bool halfOpen=true)
template<typename OpType >
static LogicalResult isIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName, bool halfOpen=true, int64_t min=0)
template<typename OpType >
static LogicalResult isSumOfIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr1, ArrayAttr arrayAttr2, ArrayRef< int64_t > shape, StringRef attrName1, StringRef attrName2, bool halfOpen=true, int64_t min=1)
static ArrayAttr makeI64ArrayAttr (ArrayRef< int64_t > values, MLIRContext *context)
static Type inferStridedSliceOpResultType (VectorType vectorType, ArrayAttr offsets, ArrayAttr sizes, ArrayAttr strides)
static LogicalResult foldExtractStridedOpFromInsertChain (ExtractStridedSliceOp op)
template<typename EmitFun >
static LogicalResult verifyPermutationMap (AffineMap permutationMap, EmitFun emitOpError)
static LogicalResult verifyTransferOp (VectorTransferOpInterface op, ShapedType shapedType, VectorType vectorType, VectorType maskType, VectorType inferredMaskType, AffineMap permutationMap, ArrayAttr inBounds)
static void printTransferAttrs (OpAsmPrinter &p, VectorTransferOpInterface op)
static VectorType inferTransferReadMaskType (VectorType vecType, AffineMap permMap)
Infers the mask type for a transfer read given its vector type and permutation map.
template<typename TransferOp >
static bool isInBounds (TransferOp op, int64_t resultIdx, int64_t indicesIdx)
template<typename TransferOp >
static LogicalResult foldTransferInBoundsAttribute (TransferOp op)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
GET_OP_LIST
#define GET_OP_LIST
Enumeration Type Documentation
MaskFormat
enum MaskFormat strong
Helper enum to classify mask value.
Enumerator
AllTrue
AllFalse
Unknown
Definition at line 53 of file VectorOps.cpp.
Function Documentation
computeBroadcastedUnitDims()
static llvm::SetVector<int64_t> computeBroadcastedUnitDims (ArrayRef< int64_t > srcShape, ArrayRef< int64_t > dstShape) static
Return the dimensions of the result vector that were formerly ones in the source tensor and thus correspond to "dim-1" broadcasting.
Definition at line 1741 of file VectorOps.cpp.
extractVector()
template<typename IntType > static SmallVector<IntType> extractVector (ArrayAttr arrayAttr) static
Definition at line 1134 of file VectorOps.cpp.
foldExtractFromBroadcast()
static Value foldExtractFromBroadcast (ExtractOp extractOp) static
Fold extractOp with scalar result coming from BroadcastOp or SplatOp.
Definition at line 1380 of file VectorOps.cpp.
References mlir::Type::dyn_cast(), mlir::Builder::getI64ArrayAttr(), mlir::Operation::getOperand(), mlir::Value::getType(), and mlir::Value::isa().
foldExtractFromExtractStrided()
static Value foldExtractFromExtractStrided (ExtractOp extractOp) static
Fold an ExtractOp from ExtractStridedSliceOp.
Definition at line 1489 of file VectorOps.cpp.
References mlir::Value::getDefiningOp(), and mlir::Builder::getI64ArrayAttr().
foldExtractFromShapeCast()
static Value foldExtractFromShapeCast (ExtractOp extractOp) static
Definition at line 1430 of file VectorOps.cpp.
References delinearize(), mlir::Value::getDefiningOp(), mlir::Builder::getI64ArrayAttr(), and mlir::linearize().
foldExtractOpFromExtractChain()
static LogicalResult foldExtractOpFromExtractChain (ExtractOp extractOp) static
Fold the result of chains of ExtractOp in place by simply concatenating the positions.
Definition at line 1142 of file VectorOps.cpp.
References mlir::failure(), mlir::Builder::getI64ArrayAttr(), and mlir::success().
foldExtractStridedOpFromInsertChain() [1/2]
static Value foldExtractStridedOpFromInsertChain (ExtractOp op) static
Fold extract_op fed from a chain of insertStridedSlice ops.
Definition at line 1530 of file VectorOps.cpp.
References mlir::Builder::getI64ArrayAttr(), mlir::Value::getType(), and mlir::Type::isa().
foldExtractStridedOpFromInsertChain() [2/2]
static LogicalResult foldExtractStridedOpFromInsertChain (ExtractStridedSliceOp op) static
Definition at line 2871 of file VectorOps.cpp.
References mlir::Value::cast(), extractStrides(), mlir::failure(), mlir::Builder::getI64ArrayAttr(), and mlir::success().
foldTransferInBoundsAttribute()
template<typename TransferOp > static LogicalResult foldTransferInBoundsAttribute (TransferOp op) static
Definition at line 3509 of file VectorOps.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::failure(), mlir::Builder::getBoolArrayAttr(), mlir::AffineMap::getPermutationMap(), mlir::AffineMap::getResult(), isInBounds(), and mlir::success().
getDimMap()
static std::vector<std::pair<int64_t, int64_t> > getDimMap (ArrayRef< AffineMap > indexingMaps, ArrayAttr iteratorTypes, IteratorType targetIteratorType, MLIRContext * context) static
Definition at line 875 of file VectorOps.cpp.
References mlir::detail::enumerate(), mlir::getAffineDimExpr(), and getResultIndex().
getMaskFormat()
static MaskFormat getMaskFormat (Value mask) static
Helper method to classify a mask value.
Currently, the method looks "under the hood" of a constant value with dense attributes and a constant mask operation (since the client may be called at various stages during progressive lowering).
Definition at line 63 of file VectorOps.cpp.
References AllFalse, AllTrue, mlir::Value::getDefiningOp(), and Unknown.
getResultIndex()
static int64_t getResultIndex (AffineMap map, AffineExpr targetExpr) static
Definition at line 867 of file VectorOps.cpp.
References mlir::AffineMap::getNumResults(), and mlir::AffineMap::getResult().
Referenced by getDimMap().
incSlicePosition()
static LogicalResult incSlicePosition (MutableArrayRef< int64_t > position, ArrayRef< int64_t > shape, ArrayRef< int64_t > offsets) static
Definition at line 220 of file VectorOps.cpp.
References mlir::failure(), and mlir::success().
inferStridedSliceOpResultType()
static Type inferStridedSliceOpResultType (VectorType vectorType, ArrayAttr offsets, ArrayAttr sizes, ArrayAttr strides) static
Definition at line 2796 of file VectorOps.cpp.
inferTransferReadMaskType()
static VectorType inferTransferReadMaskType (VectorType vecType, AffineMap permMap) static
Infers the mask type for a transfer read given its vector type and permutation map.
The mask in a transfer read operation applies to the tensor/buffer reading part of it and its type should match the shape read before any permutation or broadcasting.
Definition at line 3370 of file VectorOps.cpp.
References mlir::AffineMap::compose(), mlir::compressUnusedDims(), mlir::AffineMap::getContext(), and mlir::inversePermutation().
isInBounds()
template<typename TransferOp > static bool isInBounds (TransferOp op, int64_t resultIdx, int64_t indicesIdx) static
Definition at line 3492 of file VectorOps.cpp.
References mlir::Value::getDefiningOp().
Referenced by foldTransferInBoundsAttribute().
isIntegerArrayAttrConfinedToRange()
template<typename OpType > static LogicalResult isIntegerArrayAttrConfinedToRange (OpType op, ArrayAttr arrayAttr, int64_t min, int64_t max, StringRef attrName, bool halfOpen = true) static
Definition at line 2379 of file VectorOps.cpp.
References mlir::Attribute::cast(), max(), min(), and mlir::success().
isIntegerArrayAttrConfinedToShape()
template<typename OpType > static LogicalResult isIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName, bool halfOpen = true, int64_t min = 0) static
Definition at line 2399 of file VectorOps.cpp.
References mlir::detail::enumerate(), max(), min(), and mlir::success().
isIntegerArrayAttrSmallerThanShape()
template<typename OpType > static LogicalResult isIntegerArrayAttrSmallerThanShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName) static
Definition at line 2364 of file VectorOps.cpp.
References mlir::success().
isStepIndexArray()
static bool isStepIndexArray (ArrayAttr idxArr, uint64_t begin, size_t width) static
Definition at line 2030 of file VectorOps.cpp.
isSumOfIntegerArrayAttrConfinedToShape()
template<typename OpType > static LogicalResult isSumOfIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr1, ArrayAttr arrayAttr2, ArrayRef< int64_t > shape, StringRef attrName1, StringRef attrName2, bool halfOpen = true, int64_t min = 1) static
Definition at line 2421 of file VectorOps.cpp.
References mlir::detail::enumerate(), max(), min(), and mlir::success().
isSupportedCombiningKind()
static bool isSupportedCombiningKind (CombiningKind combiningKind, Type elementType) static
Definition at line 112 of file VectorOps.cpp.
References mlir::Type::isa(), mlir::Type::isIntOrIndex(), and mlir::Type::isIntOrIndexOrFloat().
makeI64ArrayAttr()
static ArrayAttr makeI64ArrayAttr (ArrayRef< int64_t > values, MLIRContext * context) static
Definition at line 2442 of file VectorOps.cpp.
populateFromInt64AttrArray()
static void populateFromInt64AttrArray (ArrayAttr arrayAttr, SmallVectorImpl< int64_t > & results) static
Definition at line 1720 of file VectorOps.cpp.
References mlir::Attribute::cast().
printTransferAttrs()
static void printTransferAttrs (OpAsmPrinter & p, VectorTransferOpInterface op) static
Definition at line 3339 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
verifyDimMap()
static bool verifyDimMap (VectorType lhsType, VectorType rhsType, const std::vector< std::pair< int64_t, int64_t >> & map) static
Definition at line 685 of file VectorOps.cpp.
verifyOutputShape()
static LogicalResult verifyOutputShape (ContractionOp op, VectorType lhsType, VectorType rhsType, Type accType, Type resType, const std::vector< std::pair< int64_t, int64_t >> & contractingDimMap, const std::vector< std::pair< int64_t, int64_t >> & batchDimMap) static
Definition at line 696 of file VectorOps.cpp.
References mlir::AffineMap::compose(), mlir::Type::dyn_cast(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getResults(), mlir::getUnusedDimsBitVector(), mlir::Type::isa(), mlir::simplifyAffineMap(), and mlir::success().
verifyPermutationMap()
template<typename EmitFun > static LogicalResult verifyPermutationMap (AffineMap permutationMap, EmitFun emitOpError) static
Definition at line 3225 of file VectorOps.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getResults(), and mlir::success().
verifyTransferOp()
static LogicalResult verifyTransferOp (VectorTransferOpInterface op, ShapedType shapedType, VectorType vectorType, VectorType maskType, VectorType inferredMaskType, AffineMap permutationMap, ArrayAttr inBounds) static
Definition at line 3254 of file VectorOps.cpp.
References mlir::Type::dyn_cast(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResult(), mlir::DataLayout::getTypeSizeInBits(), mlir::AffineConstantExpr::getValue(), mlir::BoolAttr::getValue(), mlir::AffineExpr::isa(), and mlir::success().